-- Auto-generated PROVIDE indicator enrichment seed

DELETE FROM indicators;

INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Days a Year with Maximum Temperatures Above X°C', 'urban-climate', 'urbclim-T2M-dayoverX');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Nights a Year with Minimum Temperatures Above X°C', 'urban-climate', 'urbclim-T2M-nightoverX');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Days a Year with Extreme Heat Stress', 'urban-climate', 'urbclim-WBGT-dayover31');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Days a Year with Very High Heat Stress', 'urban-climate', 'urbclim-WBGT-dayover295');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Days a Year with Moderate Heat Stress', 'urban-climate', 'urbclim-WBGT-dayover25');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Days a Year with High Heat Stress', 'urban-climate', 'urbclim-WBGT-dayover28');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Cooling Degree Hours', 'urban-climate', 'urbclim-cooling-degree-hours');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Hours a Year with Extreme Heat Stress', 'urban-climate', 'urbclim-WBGT-hourover31');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Mean Daily Maximum Temperature', 'urban-climate', 'urbclim-T2M-daily-mean-max');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Nights a Year with High Heat Stress', 'urban-climate', 'urbclim-WBGT-nightover28');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Lost Working Hours per Year for Moderate Activities', 'urban-climate', 'urbclim-LWH-mod');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Heat-Wave Magnitude Index Daily (HWMId)', 'urban-climate', 'urbclim-HWMI');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Mean Daily Minimum Temperature', 'urban-climate', 'urbclim-T2M-daily-mean-min');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Hours a Year with Moderate Heat Stress', 'urban-climate', 'urbclim-WBGT-hourover25');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Mean Daily Maximum Wet Bulb Globe Temperature', 'urban-climate', 'urbclim-WBGT-daily-mean-max');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Lost Working Hours per Year for Light Activities', 'urban-climate', 'urbclim-LWH-light');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Mean Daily Temperature', 'urban-climate', 'urbclim-T2M-mean');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Lost Working Hours per Year for Intense Activities', 'urban-climate', 'urbclim-LWH-int');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Hours a Year with High Heat Stress', 'urban-climate', 'urbclim-WBGT-hourover28');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Hours a Year with Very High Heat Stress', 'urban-climate', 'urbclim-WBGT-hourover295');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Heatwave Days per Year', 'urban-climate', 'urbclim-heatwave-days');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Population Exposed to Heatwaves', 'urban-climate', 'urbclim-heatwaves-population-exposed');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Population Exposed to Moderate Heatstress', 'urban-climate', 'urbclim-heatstressimpact-wbgt-dayover25');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Population Exposed to High Heat Stress', 'urban-climate', 'urbclim-heatstressimpact-wbgt-dayover28');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Population Exposed to Very High Heat Stress', 'urban-climate', 'urbclim-heatstressimpact-wbgt-dayover295');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Population Exposed to Extreme Heatstress', 'urban-climate', 'urbclim-heatstressimpact-wbgt-dayover31');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Mean Temperature', 'terrestrial-climate', 'terclim-mean-temperature');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Extremely Hot Year', 'terrestrial-climate', 'terclim-hot-extreme');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Extremely Cold Year', 'terrestrial-climate', 'terclim-cold-extreme');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Annual Maximum Temperature', 'terrestrial-climate', 'terclim-txx');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Annual Minimum of Monthly Mean Soil Moisture Content', 'terrestrial-climate', 'terclim-mrso-minmon');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Fire Weather Index During the Fire Season', 'terrestrial-climate', 'terclim-fwisa');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Length of the Fire Season', 'terrestrial-climate', 'terclim-fwils');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Soil Moisture Content', 'terrestrial-climate', 'terclim-mrso');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Annual Maximum of the Fire Weather Index', 'terrestrial-climate', 'terclim-fwixx');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Number of Days with Extreme Fire Weather', 'terrestrial-climate', 'terclim-fwixd');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Species at Risk from Local Extinction', 'biodiversity', 'biodiversity-srr');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Timber Species at Risk from Local Extinction', 'biodiversity', 'biodiversity-timber-srr');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Pollinator Species at Risk from Local Extinction', 'biodiversity', 'biodiversity-pollinators-srr');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Plant Species at Risk from Local Extinction', 'biodiversity', 'biodiversity-plantae-srr');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Glacier Area', 'glacier', 'glacier-area');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Glacier Volume', 'glacier', 'glacier-volume');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Glacier Thinning Rate', 'glacier', 'glacier-thinning_rate');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Nights a Year with Moderate Heat Stress', 'urban-climate', 'urbclim-WBGT-nightover25');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Sea Surface Temperature', 'maritime-climate', 'marclim-sst');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Sea Surface pH', 'maritime-climate', 'marclim-ph');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Ocean Oxygen Content', 'maritime-climate', 'marclim-oxygen');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Marine Heatwave Days per Year', 'maritime-climate', 'marclim-sst_ext');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Global Atmospheric CH4 Concentration from Peatland Emissions', 'carboncycle', 'carboncycle-d-ch4');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Global Atmospheric CO2 Concentration from Peatland Emissions', 'carboncycle', 'carboncycle-d-co2');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Peatland CH4 Emission', 'carboncycle', 'carboncycle-d-ept-ch4');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Peatland CO2 Flux', 'carboncycle', 'carboncycle-d-ept-co2');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Global Annual Mean Temperature Rise from Peatland Emissions', 'carboncycle', 'carboncycle-d-tg');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Climate Change Impact on GDP', 'macroeconomy', 'macroeconomy-bhm');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Export Supply (Food Sector)', 'macroeconomy', 'macroeconomy-export-supply-food');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Export Supply (Livestock Sector)', 'macroeconomy', 'macroeconomy-export-supply-livestock');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Export Supply (Manufacturing Sector)', 'macroeconomy', 'macroeconomy-export-supply-manufacturing');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Export Supply (Services Sector)', 'macroeconomy', 'macroeconomy-export-supply-services');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Private Consumption (Food Sector)', 'macroeconomy', 'macroeconomy-private-consumption-food');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Private Consumption (Livestock Sector)', 'macroeconomy', 'macroeconomy-private-consumption-livestock');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Private Consumption (Manufacturing Sector)', 'macroeconomy', 'macroeconomy-private-consumption-manufacturing');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Private Consumption (Services Sector)', 'macroeconomy', 'macroeconomy-private-consumption-services');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('GDP (All Sectors)', 'macroeconomy', 'macroeconomy-gdp-macro');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Import Demand (Food Sector)', 'macroeconomy', 'macroeconomy-import-demand-food');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Import Demand (Livestock Sector)', 'macroeconomy', 'macroeconomy-import-demand-livestock');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Import Demand (Manufacturing Sector)', 'macroeconomy', 'macroeconomy-import-demand-manufacturing');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Import Demand (Services Sector)', 'macroeconomy', 'macroeconomy-import-demand-services');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Producer Price (Food Sector)', 'macroeconomy', 'macroeconomy-producer-price-food');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Producer Price (Livestock Sector)', 'macroeconomy', 'macroeconomy-producer-price-livestock');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Producer Price (Manufacturing Sector)', 'macroeconomy', 'macroeconomy-producer-price-manufacturing');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Producer Price (Services Sector)', 'macroeconomy', 'macroeconomy-producer-price-services');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Wages (Food Sector)', 'macroeconomy', 'macroeconomy-wages-food');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Wages (Livestock Sector)', 'macroeconomy', 'macroeconomy-wages-livestock');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Wages (Manufacturing Sector)', 'macroeconomy', 'macroeconomy-wages-manufacturing');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Wages (Services Sector)', 'macroeconomy', 'macroeconomy-wages-services');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Consumer Price Index (All Sectors)', 'macroeconomy', 'macroeconomy-consumer-price-index-macro');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Production (Food Sector)', 'macroeconomy', 'macroeconomy-production-food');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Production (Livestock Sector)', 'macroeconomy', 'macroeconomy-production-livestock');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Production (Manufacturing Sector)', 'macroeconomy', 'macroeconomy-production-manufacturing');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Production (Services Sector)', 'macroeconomy', 'macroeconomy-production-services');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Labour Productivity', 'macroeconomy', 'macroeconomy-labour-productivity');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Nights a Year Where Minimum Wet-Bulb Globe Temperatures Stay Above X°C', 'urban-climate', 'urbclim-WBGT-nightoverX');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Hours a Year with Maximum Wet-Bulb Globe Temperature Above X°C', 'urban-climate', 'urbclim-WBGT-houroverX');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Daytime Urban Heat Island Corrected for Topography', 'urban-climate', 'urbclim-T2M-daily-mean-max-topography');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Nighttime Urban Heat Island Corrected for Topography', 'urban-climate', 'urbclim-T2M-daily-mean-min-topography');
