-- Auto-generated PROVIDE indicator enrichment seed

DELETE FROM indicators;

INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Days a year with maximum temperatures above X°C', 'urban-climate', 'urbclim-T2M-dayoverX');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Nights a year with minimum temperatures above X°C', 'urban-climate', 'urbclim-T2M-nightoverX');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Days a year with extreme heat stress', 'urban-climate', 'urbclim-WBGT-dayover31');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Days a year with very high heat stress', 'urban-climate', 'urbclim-WBGT-dayover295');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Days a year with moderate heat stress', 'urban-climate', 'urbclim-WBGT-dayover25');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Days a year with high heat stress', 'urban-climate', 'urbclim-WBGT-dayover28');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Cooling degree hours', 'urban-climate', 'urbclim-cooling-degree-hours');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Hours a year with extreme heat stress', 'urban-climate', 'urbclim-WBGT-hourover31');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Mean daily maximum temperature', 'urban-climate', 'urbclim-T2M-daily-mean-max');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Nights a year with high heat stress', 'urban-climate', 'urbclim-WBGT-nightover28');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Lost working hours per year for moderate activities', 'urban-climate', 'urbclim-LWH-mod');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Heat-wave magnitude index daily (HWMId)', 'urban-climate', 'urbclim-HWMI');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Mean daily minimum temperature', 'urban-climate', 'urbclim-T2M-daily-mean-min');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Hours a year with moderate heat stress', 'urban-climate', 'urbclim-WBGT-hourover25');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Mean daily maximum wet bulb globe temperature', 'urban-climate', 'urbclim-WBGT-daily-mean-max');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Lost working hours per year for light activities', 'urban-climate', 'urbclim-LWH-light');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Mean daily temperature', 'urban-climate', 'urbclim-T2M-mean');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Lost working hours per year for intense activities', 'urban-climate', 'urbclim-LWH-int');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Hours a year with high heat stress', 'urban-climate', 'urbclim-WBGT-hourover28');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Hours a year with very high heat stress', 'urban-climate', 'urbclim-WBGT-hourover295');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Heatwave days per year', 'urban-climate', 'urbclim-heatwave-days');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Population exposed to heatwaves', 'urban-climate', 'urbclim-heatwaves-population-exposed');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Population exposed to moderate heatstress', 'urban-climate', 'urbclim-heatstressimpact-wbgt-dayover25');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Population exposed to high heat stress', 'urban-climate', 'urbclim-heatstressimpact-wbgt-dayover28');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Population exposed to very high heat stress', 'urban-climate', 'urbclim-heatstressimpact-wbgt-dayover295');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Population exposed to extreme heatstress', 'urban-climate', 'urbclim-heatstressimpact-wbgt-dayover31');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Mean Temperature', 'terrestrial-climate', 'terclim-mean-temperature');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Extremely hot year', 'terrestrial-climate', 'terclim-hot-extreme');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Extremely cold year', 'terrestrial-climate', 'terclim-cold-extreme');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Annual maximum temperature', 'terrestrial-climate', 'terclim-txx');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Annual minimum of monthly mean soil moisture content', 'terrestrial-climate', 'terclim-mrso-minmon');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Fire Weather Index during the fire season', 'terrestrial-climate', 'terclim-fwisa');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Length of the fire season', 'terrestrial-climate', 'terclim-fwils');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Soil moisture content', 'terrestrial-climate', 'terclim-mrso');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Annual maximum of the fire weather index', 'terrestrial-climate', 'terclim-fwixx');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Number of days with extreme fire weather', 'terrestrial-climate', 'terclim-fwixd');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Species at risk from local extinction', 'biodiversity', 'biodiversity-srr');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Timber species at risk from local extinction', 'biodiversity', 'biodiversity-timber-srr');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Pollinator species at risk from local extinction', 'biodiversity', 'biodiversity-pollinators-srr');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Plant species at risk from local extinction', 'biodiversity', 'biodiversity-plantae-srr');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Glacier area', 'glacier', 'glacier-area');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Glacier volume', 'glacier', 'glacier-volume');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Glacier thinning rate', 'glacier', 'glacier-thinning_rate');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Nights a year with moderate heat stress', 'urban-climate', 'urbclim-WBGT-nightover25');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Sea surface temperature', 'maritime-climate', 'marclim-sst');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Sea surface pH', 'maritime-climate', 'marclim-ph');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Ocean oxygen content', 'maritime-climate', 'marclim-oxygen');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Marine heatwave days per year', 'maritime-climate', 'marclim-sst_ext');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Global atmospheric CH4 concentration from peatland emissions', 'carboncycle', 'carboncycle-d-ch4');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Global atmospheric CO2 concentration from peatland emissions', 'carboncycle', 'carboncycle-d-co2');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Peatland CH4 emission', 'carboncycle', 'carboncycle-d-ept-ch4');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Peatland CO2 flux', 'carboncycle', 'carboncycle-d-ept-co2');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Global annual mean temperature rise from peatland emissions', 'carboncycle', 'carboncycle-d-tg');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Climate change impact on GDP', 'macroeconomy', 'macroeconomy-bhm');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Export supply (food sector)', 'macroeconomy', 'macroeconomy-export-supply-food');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Export supply (livestock sector)', 'macroeconomy', 'macroeconomy-export-supply-livestock');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Export supply (manufacturing sector)', 'macroeconomy', 'macroeconomy-export-supply-manufacturing');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Export supply (services sector)', 'macroeconomy', 'macroeconomy-export-supply-services');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Private consumption (food sector)', 'macroeconomy', 'macroeconomy-private-consumption-food');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Private consumption (livestock sector)', 'macroeconomy', 'macroeconomy-private-consumption-livestock');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Private consumption (manufacturing sector)', 'macroeconomy', 'macroeconomy-private-consumption-manufacturing');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Private consumption (services sector)', 'macroeconomy', 'macroeconomy-private-consumption-services');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('GDP (all sectors)', 'macroeconomy', 'macroeconomy-gdp-macro');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Import demand (food sector)', 'macroeconomy', 'macroeconomy-import-demand-food');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Import demand (livestock sector)', 'macroeconomy', 'macroeconomy-import-demand-livestock');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Import demand (manufacturing sector)', 'macroeconomy', 'macroeconomy-import-demand-manufacturing');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Import demand (services sector)', 'macroeconomy', 'macroeconomy-import-demand-services');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Producer price (food sector)', 'macroeconomy', 'macroeconomy-producer-price-food');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Producer price (livestock sector)', 'macroeconomy', 'macroeconomy-producer-price-livestock');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Producer price (manufacturing sector)', 'macroeconomy', 'macroeconomy-producer-price-manufacturing');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Producer price (services sector)', 'macroeconomy', 'macroeconomy-producer-price-services');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Wages (food sector)', 'macroeconomy', 'macroeconomy-wages-food');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Wages (livestock sector)', 'macroeconomy', 'macroeconomy-wages-livestock');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Wages (manufacturing sector)', 'macroeconomy', 'macroeconomy-wages-manufacturing');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Wages (services sector)', 'macroeconomy', 'macroeconomy-wages-services');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Consumer price index (all sectors)', 'macroeconomy', 'macroeconomy-consumer-price-index-macro');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Production (food sector)', 'macroeconomy', 'macroeconomy-production-food');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Production (livestock sector)', 'macroeconomy', 'macroeconomy-production-livestock');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Production (manufacturing sector)', 'macroeconomy', 'macroeconomy-production-manufacturing');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Production (services sector)', 'macroeconomy', 'macroeconomy-production-services');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Labour Productivity', 'macroeconomy', 'macroeconomy-labour-productivity');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Nights a year where minimum wet-bulb globe temperatures stay above X°C', 'urban-climate', 'urbclim-WBGT-nightoverX');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Hours a year with maximum wet-bulb globe temperature above X°C', 'urban-climate', 'urbclim-WBGT-houroverX');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Daytime Urban Heat Island corrected for topography', 'urban-climate', 'urbclim-T2M-daily-mean-max-topography');
INSERT INTO indicators (id, sector, legacy_uid) VALUES ('Nighttime Urban Heat Island corrected for topography', 'urban-climate', 'urbclim-T2M-daily-mean-min-topography');
