-- Auto-generated seed file
-- Source: https://provide-api.iiasa.ac.at/api/meta/
-- Generated: 2026-04-06T20:46:34.629Z

DELETE FROM geographies;
DELETE FROM geography_types;

INSERT INTO geography_types (id, label, label_singular, "order", is_available) VALUES ('admin0', 'Countries', 'Country', 0, 1);
INSERT INTO geography_types (id, label, label_singular, "order", is_available) VALUES ('eez', 'Exclusive Economic Zones', 'Exclusive Economic Zone', 1, 1);
INSERT INTO geography_types (id, label, label_singular, "order", is_available) VALUES ('cities', 'Cities', 'City', 2, 1);
INSERT INTO geography_types (id, label, label_singular, "order", is_available) VALUES ('global', 'Global', 'Global', 3, 1);
INSERT INTO geography_types (id, label, label_singular, "order", is_available) VALUES ('glacier_regions', 'Glacier Regions', 'Glacier Region', 4, 1);
INSERT INTO geography_types (id, label, label_singular, "order", is_available) VALUES ('river_basins', 'River Basins', 'River Basin', 5, 1);
INSERT INTO geography_types (id, label, label_singular, "order", is_available) VALUES ('macroeconomy', 'Macroeconomies', 'Macroeconomy', 6, 0);

-- Countries (173 entries)
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('POL', 'Poland', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SEN', 'Senegal', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BRN', 'Brunei', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BRI', 'Brazilian Island', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SMR', 'San Marino', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('HUN', 'Hungary', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BWA', 'Botswana', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MAR', 'Morocco', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('OMN', 'Oman', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GBR', 'United Kingdom', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('NLD', 'Netherlands', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CHL', 'Chile', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SAU', 'Saudi Arabia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CHN', 'China', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('LTU', 'Lithuania', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('HND', 'Honduras', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('FIN', 'Finland', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('DEU', 'Germany', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('EGY', 'Egypt', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('NPL', 'Nepal', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('UZB', 'Uzbekistan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('AUS', 'Australia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('FRA', 'France', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('HRV', 'Croatia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('AUT', 'Austria', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BOL', 'Bolivia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('IDN', 'Indonesia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BGD', 'Bangladesh', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('TUN', 'Tunisia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MWI', 'Malawi', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CAF', 'Central African Rep.', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BGR', 'Bulgaria', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CAN', 'Canada', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('DNK', 'Denmark', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('AND', 'Andorra', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('NIC', 'Nicaragua', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('KHM', 'Cambodia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('TUR', 'Turkey', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CIV', 'Côte d''Ivoire', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GTM', 'Guatemala', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('LBR', 'Liberia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('LBN', 'Lebanon', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('LUX', 'Luxembourg', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CRI', 'Costa Rica', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('AFG', 'Afghanistan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('LBY', 'Libya', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MOZ', 'Mozambique', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('LVA', 'Latvia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('IMN', 'Isle of Man', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('NAM', 'Namibia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('PRK', 'Dem. Rep. Korea', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('PER', 'Peru', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CYP', 'Cyprus', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ABW', 'Aruba', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('JOR', 'Jordan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BDI', 'Burundi', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BLR', 'Belarus', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('PRT', 'Portugal', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('TJK', 'Tajikistan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GIB', 'Gibraltar', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('NZL', 'New Zealand', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MLI', 'Mali', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CZE', 'Czechia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('PRY', 'Paraguay', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('COG', 'Republic of the Congo', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GIN', 'Guinea', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BLZ', 'Belize', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('IND', 'India', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MDA', 'Moldova', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('RWA', 'Rwanda', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('COD', 'Democratic Republic of the Congo', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GAB', 'Gabon', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('UGA', 'Uganda', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ZAF', 'South Africa', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MDG', 'Madagascar', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('COL', 'Colombia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('KAZ', 'Kazakhstan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('IRQ', 'Iraq', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SYR', 'Syria', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BEN', 'Benin', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('PSX', 'Palestine', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GRC', 'Greece', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('TCD', 'Chad', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('LKA', 'Sri Lanka', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BEL', 'Belgium', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ALB', 'Albania', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('TKM', 'Turkmenistan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ROU', 'Romania', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('NGA', 'Nigeria', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('LSO', 'Lesotho', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GRL', 'Greenland', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('VNM', 'Vietnam', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BFA', 'Burkina Faso', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MMR', 'Myanmar', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ISL', 'Iceland', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GNQ', 'Eq. Guinea', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SAH', 'W. Sahara', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SRB', 'Serbia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CHE', 'Switzerland', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ISR', 'Israel', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ZWE', 'Zimbabwe', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SVN', 'Slovenia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MNE', 'Montenegro', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('NOR', 'Norway', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('KOR', 'Republic of Korea', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MNG', 'Mongolia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('THA', 'Thailand', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('EST', 'Estonia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SVK', 'Slovakia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ITA', 'Italy', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('KWT', 'Kuwait', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ESP', 'Spain', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('DZA', 'Algeria', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MEX', 'Mexico', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('KOS', 'Kosovo', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MRT', 'Mauritania', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('KGZ', 'Kyrgyzstan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('JEY', 'Jersey', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('LAO', 'Laos', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CUW', 'Curaçao', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('PHL', 'Philippines', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('YEM', 'Yemen', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ECU', 'Ecuador', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SWE', 'Sweden', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ETH', 'Ethiopia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ARE', 'United Arab Emirates', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MKD', 'North Macedonia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ARG', 'Argentina', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('AZE', 'Azerbaijan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GGY', 'Guernsey', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CMR', 'Cameroon', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('DJI', 'Djibouti', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ARM', 'Armenia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SWZ', 'eSwatini', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GHA', 'Ghana', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('LIE', 'Liechtenstein', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('RUS', 'Russia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SOM', 'Somalia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BTN', 'Bhutan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SGP', 'Singapore', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('NER', 'Niger', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('URY', 'Uruguay', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GMB', 'Gambia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ZMB', 'Zambia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MCO', 'Monaco', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('PAN', 'Panama', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('USA', 'United States', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SLE', 'Sierra Leone', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GUF', 'French Guiana', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('PAK', 'Pakistan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('DOM', 'Dominican Rep.', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('KEN', 'Kenya', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('IRL', 'Ireland', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('IRN', 'Iran', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GUY', 'Guyana', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SDN', 'Sudan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('PNG', 'Papua New Guinea', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SLV', 'El Salvador', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ERI', 'Eritrea', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('TZA', 'Tanzania', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GEO', 'Georgia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('UKR', 'Ukraine', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('AGO', 'Angola', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('TWN', 'Taiwan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SDS', 'S. Sudan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('VEN', 'Venezuela', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BIH', 'Bosnia and Herz.', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('JPN', 'Japan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MYS', 'Malaysia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('TGO', 'Togo', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BRA', 'Brazil', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SUR', 'Suriname', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GNB', 'Guinea-Bissau', 'admin0', NULL);

-- Exclusive Economic Zones (175 entries)
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('LBR-eez', 'Liberia', 'eez', 'LBR');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MMR-eez', 'Myanmar', 'eez', 'MMR');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('LBN-eez', 'Lebanon', 'eez', 'LBN');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MUS-eez', 'Republic of Mauritius', 'eez', 'MUS');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BRN-eez', 'Brunei', 'eez', 'BRN');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('KHM-eez', 'Cambodia', 'eez', 'KHM');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('VCT-eez', 'Saint Vincent and the Grenadines', 'eez', 'VCT');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('NGA-eez', 'Nigeria', 'eez', 'NGA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ROU-eez', 'Romania', 'eez', 'ROU');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('IDN-eez', 'Indonesia', 'eez', 'IDN');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('VEN-eez', 'Venezuela', 'eez', 'VEN');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BRA-eez', 'Brazil', 'eez', 'BRA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BRB-eez', 'Barbados', 'eez', 'BRB');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GRC-eez', 'Greece', 'eez', 'GRC');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GRD-eez', 'Grenada', 'eez', 'GRD');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('PHL-eez', 'Philippines', 'eez', 'PHL');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('TZA-eez', 'Tanzania', 'eez', 'TZA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SWE-eez', 'Sweden', 'eez', 'SWE');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('UKR-eez', 'Ukraine', 'eez', 'UKR');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('AGO-eez', 'Angola', 'eez', 'AGO');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GIN-eez', 'Guinea', 'eez', 'GIN');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BGD-eez', 'Bangladesh', 'eez', 'BGD');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MRT-eez', 'Mauritania', 'eez', 'MRT');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('VUT-eez', 'Vanuatu', 'eez', 'VUT');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('IND-eez', 'India', 'eez', 'IND');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GAB-eez', 'Gabon', 'eez', 'GAB');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('KIR-eez', 'Phoenix Group', 'eez', 'KIR');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('HTI-eez', 'Navassa Island', 'eez', 'HTI');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('THA-eez', 'Thailand', 'eez', 'THA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('PAN-eez', 'Panama', 'eez', 'PAN');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('EST-eez', 'Estonia', 'eez', 'EST');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CHN-eez', 'China', 'eez', 'CHN');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CPV-eez', 'Cape Verde', 'eez', 'CPV');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('PAK-eez', 'Pakistan', 'eez', 'PAK');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ESP-eez', 'Spain', 'eez', 'ESP');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('LCA-eez', 'Saint Lucia', 'eez', 'LCA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SAH-eez', 'Western Sahara', 'eez', 'SAH');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ISL-eez', 'Iceland', 'eez', 'ISL');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GNQ-eez', 'Equatorial Guinea', 'eez', 'GNQ');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CRI-eez', 'Costa Rica', 'eez', 'CRI');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CAN-eez', 'Canada', 'eez', 'CAN');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GHA-eez', 'Ghana', 'eez', 'GHA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CIV-eez', 'Ivory Coast', 'eez', 'CIV');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('RUS-eez', 'Russia', 'eez', 'RUS');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SOM-eez', 'Federal Republic of Somalia', 'eez', 'SOM');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BGR-eez', 'Bulgaria', 'eez', 'BGR');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ECU-eez', 'Ecuador', 'eez', 'ECU');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('COL-eez', 'Colombia', 'eez', 'COL');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('COM-eez', 'Comores', 'eez', 'COM');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('COG-eez', 'Republic of the Congo', 'eez', 'COG');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('NRU-eez', 'Nauru', 'eez', 'NRU');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SDN-eez', 'Sudan', 'eez', 'SDN');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('COD-eez', 'Democratic Republic of the Congo', 'eez', 'COD');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('DZA-eez', 'Algeria', 'eez', 'DZA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SLV-eez', 'El Salvador', 'eez', 'SLV');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('PNG-eez', 'Papua New Guinea', 'eez', 'PNG');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MHL-eez', 'Marshall Islands', 'eez', 'MHL');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GMB-eez', 'Gambia', 'eez', 'GMB');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('KOR-eez', 'South Korea', 'eez', 'KOR');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('STP-eez', 'Sao Tome and Principe', 'eez', 'STP');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BLZ-eez', 'Belize', 'eez', 'BLZ');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('FSM-eez', 'Micronesia', 'eez', 'FSM');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ITA-eez', 'Italy', 'eez', 'ITA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SLE-eez', 'Sierra Leone', 'eez', 'SLE');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SLB-eez', 'Solomon Islands', 'eez', 'SLB');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('DOM-eez', 'Dominican Republic', 'eez', 'DOM');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ISR-eez', 'Israel', 'eez', 'ISR');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MAR-eez', 'Morocco', 'eez', 'MAR');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('TGO-eez', 'Togo', 'eez', 'TGO');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('OMN-eez', 'Oman', 'eez', 'OMN');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SEN-eez', 'Senegal', 'eez', 'SEN');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('TON-eez', 'Tonga', 'eez', 'TON');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ATG-eez', 'Antigua and Barbuda', 'eez', 'ATG');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MYS-eez', 'Malaysia', 'eez', 'MYS');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GNB-eez', 'Guinea-Bissau', 'eez', 'GNB');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('TWN-eez', 'Taiwan', 'eez', 'TWN');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('PLW-eez', 'Palau', 'eez', 'PLW');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SUR-eez', 'Suriname', 'eez', 'SUR');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BEN-eez', 'Benin', 'eez', 'BEN');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ERI-eez', 'Eritrea', 'eez', 'ERI');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GEO-eez', 'Georgia', 'eez', 'GEO');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('IRL-eez', 'Ireland', 'eez', 'IRL');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GUY-eez', 'Guyana', 'eez', 'GUY');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('TLS-eez', 'Timor Leste', 'eez', 'TLS');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('KNA-eez', 'Saint Kitts and Nevis', 'eez', 'KNA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('WSM-eez', 'Samoa', 'eez', 'WSM');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ZAF-eez', 'South Africa', 'eez', 'ZAF');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('LTU-eez', 'Lithuania', 'eez', 'LTU');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('TTO-eez', 'Trinidad and Tobago', 'eez', 'TTO');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CUB-eez', 'Cuba', 'eez', 'CUB');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('KEN-eez', 'Kenya', 'eez', 'KEN');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('PER-eez', 'Peru', 'eez', 'PER');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SAU-eez', 'Saudi Arabia', 'eez', 'SAU');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MOZ-eez', 'Mozambique', 'eez', 'MOZ');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('NAM-eez', 'Namibia', 'eez', 'NAM');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('LVA-eez', 'Latvia', 'eez', 'LVA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('DMA-eez', 'Dominica', 'eez', 'DMA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('VNM-eez', 'Vietnam', 'eez', 'VNM');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('TUV-eez', 'Tuvalu', 'eez', 'TUV');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GTM-eez', 'Guatemala', 'eez', 'GTM');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('FJI-eez', 'Fiji', 'eez', 'FJI');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('NIC-eez', 'Nicaragua', 'eez', 'NIC');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('TUR-eez', 'Turkey', 'eez', 'TUR');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('TUN-eez', 'Tunisia', 'eez', 'TUN');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ARG-eez', 'Argentina', 'eez', 'ARG');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CMR-eez', 'Cameroon', 'eez', 'CMR');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('JPN-eez', 'Japan', 'eez', 'JPN');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('LKA-eez', 'Sri Lanka', 'eez', 'LKA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MDV-eez', 'Maldives', 'eez', 'MDV');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('EGY-eez', 'Egypt', 'eez', 'EGY');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MLT-eez', 'Malta', 'eez', 'MLT');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SYC-eez', 'Seychelles', 'eez', 'SYC');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('DEU-eez', 'Germany', 'eez', 'DEU');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('YEM-eez', 'Yemen', 'eez', 'YEM');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MDG-eez', 'Madagascar', 'eez', 'MDG');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('HND-eez', 'Honduras', 'eez', 'HND');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('JAM-eez', 'Jamaica', 'eez', 'JAM');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BHS-eez', 'Bahamas', 'eez', 'BHS');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('LBY-eez', 'Libya', 'eez', 'LBY');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('PRT-eez', 'Portugal', 'eez', 'PRT');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MEX-eez', 'Mexico', 'eez', 'MEX');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('URY-eez', 'Uruguay', 'eez', 'URY');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('PRK-eez', 'North Korea', 'eez', 'PRK');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('NOR-eez', 'Norway', 'eez', 'NOR');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CYP-eez', 'Cyprus', 'eez', 'CYP');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('PYF-eez', 'French Polynesia', 'eez', 'PYF');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('FRA-MYT-eez', 'Mayotte', 'eez', 'FRA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('FRA-TFF-eez', 'Ile Tromelin', 'eez', 'FRA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('NCL-eez', 'New Caledonia', 'eez', 'NCL');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('FRA-REU-eez', 'La Reunion', 'eez', 'FRA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('FRA-MHI-eez', 'Matthew and Hunter Islands', 'eez', 'FRA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('FRA-CPT-eez', 'Clipperton Island', 'eez', 'FRA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('FRA-GLP-eez', 'Guadeloupe', 'eez', 'FRA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BLM-eez', 'Saint Barthelemy', 'eez', 'BLM');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MAF-eez', 'Collectivity of Saint Martin', 'eez', 'MAF');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SPM-eez', 'Saint-Pierre and Miquelon', 'eez', 'SPM');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('FRA-MTQ-eez', 'Martinique', 'eez', 'FRA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GUF-eez', 'French Guiana', 'eez', 'GUF');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('FRA-eez', 'France', 'eez', 'FRA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ATF-eez', 'Amsterdam and Saint Paul Islands', 'eez', 'ATF');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('FLK-eez', 'Falkland / Malvinas Islands', 'eez', 'FLK');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GBR-PCA-eez', 'Pitcairn', 'eez', 'GBR');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('AIA-eez', 'Anguilla', 'eez', 'AIA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('VGB-eez', 'British Virgin Islands', 'eez', 'VGB');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CYM-eez', 'Cayman Islands', 'eez', 'CYM');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MSR-eez', 'Montserrat', 'eez', 'MSR');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('TCA-eez', 'Turks and Caicos Islands', 'eez', 'TCA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GBR-SGS-eez', 'South Georgia and the South Sandwich Islands', 'eez', 'GBR');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('BMU-eez', 'Bermuda', 'eez', 'BMU');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GBR-eez', 'United Kingdom', 'eez', 'GBR');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('SHN-eez', 'St Helene, Ascension and Tristan da Cunha', 'eez', 'SHN');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ASM-eez', 'American Samoa', 'eez', 'ASM');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('VIR-eez', 'United States Virgin Islands', 'eez', 'VIR');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GUM-eez', 'Guam', 'eez', 'GUM');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('MNP-eez', 'Northern Mariana Islands', 'eez', 'MNP');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('USA-HI-eez', 'Hawaii', 'eez', 'USA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('USA-AK-eez', 'Alaska', 'eez', 'USA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('USA-eez', 'United States', 'eez', 'USA');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('UMI-eez', 'Palmyra Atoll', 'eez', 'UMI');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('PRI-eez', 'Puerto Rico', 'eez', 'PRI');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('NLD-eez', 'Netherland', 'eez', 'NLD');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ABW-eez', 'Caribbean Netherlands', 'eez', 'ABW');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('COK-eez', 'Cook Islands', 'eez', 'COK');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('NZL-eez', 'New Zealand', 'eez', 'NZL');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CHL-eez', 'Chile', 'eez', 'CHL');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CHL-EIA-eez', 'Easter Islands', 'eez', 'CHL');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('CHL-SFA-eez', 'San Felix and San Ambrosia islands', 'eez', 'CHL');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('AUS-eez', 'Australia', 'eez', 'AUS');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('AUS-MCI-eez', 'Macquire Island', 'eez', 'AUS');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('AUS-NCK-eez', 'Norfolk Island', 'eez', 'AUS');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('AUS-HMD-eez', 'Heard and McDonald Islands', 'eez', 'AUS');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('AUS-CCK-eez', 'Cocos Islands', 'eez', 'AUS');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('AUS-CIL-eez', 'Christmas Islands', 'eez', 'AUS');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('DNK-eez', 'Denmark', 'eez', 'DNK');
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('GRL-eez', 'Greenland', 'eez', 'GRL');

-- Cities (144 entries)
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('accra', 'Accra', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('addis_abeba', 'Addis Abeba', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('alicante', 'Alicante', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('amman', 'Amman', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('amsterdam', 'Amsterdam', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('antwerp', 'Antwerp', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('athens', 'Athens', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('auckland', 'Auckland', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('barcelona', 'Barcelona', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('bari', 'Bari', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('basel', 'Basel', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('belgrado', 'Belgrade', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('berlin', 'Berlin', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('bilbao', 'Bilbao', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('birmingham', 'Birmingham', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('bodo', 'Bodø', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('bogota', 'Bogota', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('bologna', 'Bologna', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('bordeaux', 'Bordeaux', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('brasov', 'Brasov', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('bratislava', 'Bratislava', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('brussels', 'Brussels', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('bucharest', 'Bucharest', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('budapest', 'Budapest', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('buenos_aires', 'Buenos Aires', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('cairo', 'Cairo', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('cape_town', 'Cape Town', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('charleroi', 'Charleroi', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('chennai', 'Chennai', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('cluj_napoca', 'Cluj Napoca', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('cologne', 'Cologne', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('copenhagen', 'Copenhagen', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('curitiba', 'Curitiba', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('dakar', 'Dakar', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('debrecen', 'Debrecen', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('dhaka', 'Dhaka', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('dubai', 'Dubai', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('dublin', 'Dublin', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('dusseldorf', 'Dusseldorf', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('edinburgh', 'Edinburgh', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('frankfurt_am_main', 'Frankfurt am Main', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('gdansk', 'Gdansk', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('geneva', 'Geneva', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('genoa', 'Genoa', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ghent', 'Ghent', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('glasgow', 'Glasgow', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('goteborg', 'Goteborg', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('graz', 'Graz', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('gyor', 'Gyor', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('hamburg', 'Hamburg', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('helsinki', 'Helsinki', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ho_chi_minh', 'Ho Chi Minh', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('hong_kong', 'Hong Kong', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('houston', 'Houston', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('istanbul', 'Istanbul', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('islamabad', 'Islamabad', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('jakarta', 'Jakarta', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('karachi', 'Karachi', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('klaipeda', 'Klaipeda', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('kosice', 'Kosice', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('krakow', 'Krakow', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('lagos', 'Lagos', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('leeds', 'Leeds', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('leipzig', 'Leipzig', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('liege', 'Liege', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('lille', 'Lille', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('lima', 'Lima', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('lisbon', 'Lisbon', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ljubljana', 'Ljubljana', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('lodz', 'Lodz', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('london', 'London', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('los_angeles', 'Los Angeles', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('luxembourg', 'Luxembourg', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('lyon', 'Lyon', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('madrid', 'Madrid', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('malaga', 'Malaga', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('marrakesh', 'Marrakesh', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('marseille', 'Marseille', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('medina', 'Medina', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('melbourne', 'Melbourne', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('mexico_city', 'Mexico City', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('milan', 'Milan', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('miskolc', 'Miskolc', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('mogadishu', 'Mogadishu', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('montpellier', 'Montpellier', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('moscow', 'Moscow', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('munich', 'Munich', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('murcia', 'Murcia', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('nairobi', 'Nairobi', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('nanjing', 'Nanjing', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('nantes', 'Nantes', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('naples', 'Naples', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('nassau', 'Nassau', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('new_york', 'New York', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('newcastle', 'Newcastle', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('nice', 'Nice', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('novi_sad', 'Novi Sad', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('oslo', 'Oslo', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('padua', 'Padua', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('palermo', 'Palermo', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('palma_de_mallorca', 'Palma de Mallorca', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('paris', 'Paris', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('pecs', 'Pecs', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('phoenix', 'Phoenix', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('podgorica', 'Podgorica', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('porto', 'Porto', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('prague', 'Prague', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('rabat', 'Rabat', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('reykjavik', 'Reykjavik', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('riga', 'Riga', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('rome', 'Rome', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('rotterdam', 'Rotterdam', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('salvador', 'Salvador', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('santiago', 'Santiago', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('sarajevo', 'Sarajevo', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('sevilla', 'Sevilla', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('singapore', 'Singapore', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('skopje', 'Skopje', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('sofia', 'Sofia', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('split', 'Split', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('stockholm', 'Stockholm', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('strasbourg', 'Strasbourg', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('sydney', 'Sydney', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('szeged', 'Szeged', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('tallinn', 'Tallinn', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('tartu', 'Tartu', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('teheran', 'Teheran', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('thessaloniki', 'Thessaloniki', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('tirana', 'Tirana', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('tokyo', 'Tokyo', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('toronto', 'Toronto', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('toulouse', 'Toulouse', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('trieste', 'Trieste', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('tschwane', 'Tschwane', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('turin', 'Turin', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('utrecht', 'Utrecht', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('valencia', 'Valencia', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('varna', 'Varna', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('vienna', 'Vienna', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('vilnius', 'Vilnius', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('warsaw', 'Warsaw', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('wroclaw', 'Wroclaw', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('zagreb', 'Zagreb', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('zurich', 'Zurich', 'cities', NULL);

-- Global (2 entries)
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('northernlats', 'Northern Latitudes', 'global', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('global', 'Global', 'global', NULL);

-- Glacier Regions (13 entries)
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('arctic_canada', 'Arctic Canada', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('caucasus_and_middle_east', 'Caucasus and Middle East', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('central_asia', 'Central Asia', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('central_europe', 'Central Europe', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('east_asia', 'East Asia', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('greenland_periphery', 'Greenland Periphery', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('new_zealand', 'New Zealand', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('northern_andes', 'Northern Andes', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('scandinavia_and_iceland', 'Scandinavia and Iceland', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('southern_andes', 'Southern Andes', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('subantarctic_and_antarctic_islands', 'Subantarctic and Antarctic Islands', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('svalbard,_jan_mayen_and_russian_arctic', 'Svalbard, Jan Mayen and Russian Arctic', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('western_canada_and_usa', 'Western Canada and USA', 'glacier_regions', NULL);

-- River Basins (75 entries)
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('indigirka', 'Indigirka', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ob', 'Ob', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('brahmaputra', 'Brahmaputra', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ganges', 'Ganges', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('indus', 'Indus', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('irrawaddy', 'Irrawaddy', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('salween', 'Salween', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('kamchatka', 'Kamchatka', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('mekong', 'Mekong', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('yangtze', 'Yangtze', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('yellow_river', 'Yellow River', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('aral_sea', 'Aral Sea', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('chuy', 'Chuy', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('har_us_nuur', 'Har Us Nuur', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('lake_balkhash', 'Lake Balkhash', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('talas', 'Talas', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('tarim_he', 'Tarim He', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('uvs_nuur', 'Uvs Nuur', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ysyk-kol', 'Ysyk Kol', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('amazon', 'Amazon', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('chico', 'Chico', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('colorado', 'Colorado', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('magdalena', 'Magdalena', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('negro', 'Negro', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('santa_cruz', 'Santa Cruz', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('aisen', 'Aisen', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('azopardo', 'Azopardo', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('baker', 'Baker', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('biobio', 'Biobio', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('cisnes', 'Cisnes', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('copiapo', 'Copiapo', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('huasco', 'Huasco', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('majes', 'Majes', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('ocona', 'Ocona', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('palena', 'Palena', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('pascua', 'Pascua', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('puelo', 'Puelo', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('rapel', 'Rapel', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('santa', 'Santa', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('serrano', 'Serrano', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('valdivia', 'Valdivia', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('yelcho', 'Yelcho', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('titicaca', 'Titicaca', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('colville', 'Colville', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('mackenzie', 'Mackenzie', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('nelson', 'Nelson', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('alsek', 'Alsek', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('columbia', 'Columbia', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('copper', 'Copper', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('fraser', 'Fraser', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('kuskokwim', 'Kuskokwim', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('nass', 'Nass', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('nushagak', 'Nushagak', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('skagit', 'Skagit', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('skeena', 'Skeena', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('stikine', 'Stikine', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('susitna', 'Susitna', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('taku', 'Taku', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('yukon', 'Yukon', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('clutha', 'Clutha', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('jokulsa_a_fjollum', 'Jokulsa a Fjollum', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('lagarfljot', 'Lagarfljot', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('svarta', 'Svarta', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('danube', 'Danube', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('dramselva', 'Dramselva', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('glomaa', 'Glomaa', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('kalixalven', 'Kalixalven', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('kuban', 'Kuban', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('lulealven', 'Lulealven', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('olfusa', 'Olfusa', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('po', 'Po', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('rhine', 'Rhine', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('rhone', 'Rhone', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('thjorsa', 'Thjorsa', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('tornealven', 'Tornealven', 'river_basins', NULL);

-- Macroeconomies (14 entries)
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('central-africa', 'Central Africa', 'macroeconomy', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('east-africa', 'East Africa', 'macroeconomy', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('east-asia', 'East Asia', 'macroeconomy', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('europe', 'Europe', 'macroeconomy', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('north-africa', 'North Africa', 'macroeconomy', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('north-america', 'North America', 'macroeconomy', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('oceania', 'Oceania', 'macroeconomy', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('former-soviet-union', 'Former Soviet Union', 'macroeconomy', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('south-africa', 'South Africa', 'macroeconomy', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('south-america', 'South America', 'macroeconomy', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('south-asia', 'South Asia', 'macroeconomy', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('south-east-asia', 'South East Asia', 'macroeconomy', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('west-africa', 'West Africa', 'macroeconomy', NULL);
INSERT INTO geographies (id, label, geography_type, shared_id) VALUES ('west-asia', 'West Asia', 'macroeconomy', NULL);
