-- Auto-generated PROVIDE indicator enrichment seed

DELETE FROM indicators;

INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Days a Year with Maximum Temperatures above X°C', 'urban-climate', 'urbclim-T2M-dayoverX', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Nights a Year with Minimum Temperatures above X°C', 'urban-climate', 'urbclim-T2M-nightoverX', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Days a Year with Extreme Heat Stress', 'urban-climate', 'urbclim-WBGT-dayover31', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Days a Year with Very High Heat Stress', 'urban-climate', 'urbclim-WBGT-dayover295', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Days a Year with Moderate Heat Stress', 'urban-climate', 'urbclim-WBGT-dayover25', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Days a Year with High Heat Stress', 'urban-climate', 'urbclim-WBGT-dayover28', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Cooling Degree Hours', 'urban-climate', 'urbclim-cooling-degree-hours', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Hours a Year with Extreme Heat Stress', 'urban-climate', 'urbclim-WBGT-hourover31', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Mean Daily Maximum Temperature', 'urban-climate', 'urbclim-T2M-daily-mean-max', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Nights a Year with High Heat Stress', 'urban-climate', 'urbclim-WBGT-nightover28', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Lost Working Hours per Year for Moderate Activities', 'urban-climate', 'urbclim-LWH-mod', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Heat-Wave Magnitude Index Daily (HWMId)', 'urban-climate', 'urbclim-HWMI', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Mean Daily Minimum Temperature', 'urban-climate', 'urbclim-T2M-daily-mean-min', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Hours a Year with Moderate Heat Stress', 'urban-climate', 'urbclim-WBGT-hourover25', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Mean Daily Maximum Wet Bulb Globe Temperature', 'urban-climate', 'urbclim-WBGT-daily-mean-max', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Lost Working Hours per Year for Light Activities', 'urban-climate', 'urbclim-LWH-light', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Mean Daily Temperature', 'urban-climate', 'urbclim-T2M-mean', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Lost Working Hours per Year for Intense Activities', 'urban-climate', 'urbclim-LWH-int', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Hours a Year with High Heat Stress', 'urban-climate', 'urbclim-WBGT-hourover28', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Hours a Year with Very High Heat Stress', 'urban-climate', 'urbclim-WBGT-hourover295', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Heatwave Days per Year', 'urban-climate', 'urbclim-heatwave-days', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Population Exposed to Heatwaves', 'urban-climate', 'urbclim-heatwaves-population-exposed', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Population Exposed to Moderate Heatstress', 'urban-climate', 'urbclim-heatstressimpact-wbgt-dayover25', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Population Exposed to High Heat Stress', 'urban-climate', 'urbclim-heatstressimpact-wbgt-dayover28', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Population Exposed to Very High Heat Stress', 'urban-climate', 'urbclim-heatstressimpact-wbgt-dayover295', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Population Exposed to Extreme Heatstress', 'urban-climate', 'urbclim-heatstressimpact-wbgt-dayover31', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Mean Temperature', 'terrestrial-climate', 'terclim-mean-temperature', 'degrees-celsius', -1, 'default');
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Extremely Hot Year', 'terrestrial-climate', 'terclim-hot-extreme', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Extremely Cold Year', 'terrestrial-climate', 'terclim-cold-extreme', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Annual Maximum Temperature', 'terrestrial-climate', 'terclim-txx', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Annual Minimum of Monthly Mean Soil Moisture Content', 'terrestrial-climate', 'terclim-mrso-minmon', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Fire Weather Index during the Fire Season', 'terrestrial-climate', 'terclim-fwisa', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Length of the Fire Season', 'terrestrial-climate', 'terclim-fwils', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Soil Moisture Content', 'terrestrial-climate', 'terclim-mrso', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Annual Maximum of the Fire Weather Index', 'terrestrial-climate', 'terclim-fwixx', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Number of Days with Extreme Fire Weather', 'terrestrial-climate', 'terclim-fwixd', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Species at Risk from Local Extinction', 'biodiversity', 'biodiversity-srr', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Timber Species at Risk from Local Extinction', 'biodiversity', 'biodiversity-timber-srr', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Pollinator Species at Risk from Local Extinction', 'biodiversity', 'biodiversity-pollinators-srr', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Plant Species at Risk from Local Extinction', 'biodiversity', 'biodiversity-plantae-srr', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Glacier Area', 'glacier', 'glacier-area', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Glacier Volume', 'glacier', 'glacier-volume', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Glacier Thinning Rate', 'glacier', 'glacier-thinning_rate', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Nights a Year with Moderate Heat Stress', 'urban-climate', 'urbclim-WBGT-nightover25', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Sea Surface Temperature', 'maritime-climate', 'marclim-sst', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Sea Surface pH', 'maritime-climate', 'marclim-ph', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Ocean Oxygen Content', 'maritime-climate', 'marclim-oxygen', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Marine Heatwave Days per Year', 'maritime-climate', 'marclim-sst_ext', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Global Atmospheric CH4 Concentration from Peatland Emissions', 'carboncycle', 'carboncycle-d-ch4', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Global Atmospheric CO2 Concentration from Peatland Emissions', 'carboncycle', 'carboncycle-d-co2', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Peatland CH4 Emission', 'carboncycle', 'carboncycle-d-ept-ch4', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Peatland CO2 Flux', 'carboncycle', 'carboncycle-d-ept-co2', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Global Annual Mean Temperature Rise from Peatland Emissions', 'carboncycle', 'carboncycle-d-tg', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Climate Change Impact on GDP', 'macroeconomy', 'macroeconomy-bhm', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Export Supply (Food Sector)', 'macroeconomy', 'macroeconomy-export-supply-food', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Export Supply (Livestock Sector)', 'macroeconomy', 'macroeconomy-export-supply-livestock', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Export Supply (Manufacturing Sector)', 'macroeconomy', 'macroeconomy-export-supply-manufacturing', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Export Supply (Services Sector)', 'macroeconomy', 'macroeconomy-export-supply-services', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Private Consumption (Food Sector)', 'macroeconomy', 'macroeconomy-private-consumption-food', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Private Consumption (Livestock Sector)', 'macroeconomy', 'macroeconomy-private-consumption-livestock', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Private Consumption (Manufacturing Sector)', 'macroeconomy', 'macroeconomy-private-consumption-manufacturing', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Private Consumption (Services Sector)', 'macroeconomy', 'macroeconomy-private-consumption-services', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('GDP (All Sectors)', 'macroeconomy', 'macroeconomy-gdp-macro', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Import Demand (Food Sector)', 'macroeconomy', 'macroeconomy-import-demand-food', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Import Demand (Livestock Sector)', 'macroeconomy', 'macroeconomy-import-demand-livestock', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Import Demand (Manufacturing Sector)', 'macroeconomy', 'macroeconomy-import-demand-manufacturing', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Import Demand (Services Sector)', 'macroeconomy', 'macroeconomy-import-demand-services', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Producer Price (Food Sector)', 'macroeconomy', 'macroeconomy-producer-price-food', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Producer Price (Livestock Sector)', 'macroeconomy', 'macroeconomy-producer-price-livestock', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Producer Price (Manufacturing Sector)', 'macroeconomy', 'macroeconomy-producer-price-manufacturing', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Producer Price (Services Sector)', 'macroeconomy', 'macroeconomy-producer-price-services', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Wages (Food Sector)', 'macroeconomy', 'macroeconomy-wages-food', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Wages (Livestock Sector)', 'macroeconomy', 'macroeconomy-wages-livestock', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Wages (Manufacturing Sector)', 'macroeconomy', 'macroeconomy-wages-manufacturing', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Wages (Services Sector)', 'macroeconomy', 'macroeconomy-wages-services', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Consumer Price Index (All Sectors)', 'macroeconomy', 'macroeconomy-consumer-price-index-macro', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Production (Food Sector)', 'macroeconomy', 'macroeconomy-production-food', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Production (Livestock Sector)', 'macroeconomy', 'macroeconomy-production-livestock', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Production (Manufacturing Sector)', 'macroeconomy', 'macroeconomy-production-manufacturing', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Production (Services Sector)', 'macroeconomy', 'macroeconomy-production-services', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Labour Productivity', 'macroeconomy', 'macroeconomy-labour-productivity', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Nights a Year where Minimum Wet-Bulb Globe Temperatures Stay above X°C', 'urban-climate', 'urbclim-WBGT-nightoverX', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Hours a Year with Maximum Wet-Bulb Globe Temperature above X°C', 'urban-climate', 'urbclim-WBGT-houroverX', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Daytime Urban Heat Island Corrected for Topography', 'urban-climate', 'urbclim-T2M-daily-mean-max-topography', NULL, NULL, NULL);
INSERT INTO indicators (id, sector, legacy_uid, unit, direction, color_scale) VALUES ('Nighttime Urban Heat Island Corrected for Topography', 'urban-climate', 'urbclim-T2M-daily-mean-min-topography', NULL, NULL, NULL);
