-- Auto-generated PROVIDE geographies seed
-- Source: /Users/rodrigo/WorkWorkWorkWorkWorkWork/iiasa/provide/api/db/geographies.yaml
-- Generated: 2026-06-18T11:53:17.759Z

DELETE FROM geographies;
DELETE FROM geography_types;

-- Geography types (id is a stable slug; label is the human heading)
INSERT INTO geography_types (id, label, label_singular, "order", is_available) VALUES ('admin0', 'Countries', 'Country', 0, 1);
INSERT INTO geography_types (id, label, label_singular, "order", is_available) VALUES ('eez', 'Exclusive Economic Zones (EEZ)', 'Exclusive Economic Zone (EEZ)', 1, 1);
INSERT INTO geography_types (id, label, label_singular, "order", is_available) VALUES ('cities', 'Cities', 'City', 2, 1);
INSERT INTO geography_types (id, label, label_singular, "order", is_available) VALUES ('river_basins', 'River Basins (RB)', 'River Basin (RB)', 3, 1);
INSERT INTO geography_types (id, label, label_singular, "order", is_available) VALUES ('glacier_regions', 'Glacier Regions (GR)', 'Glacier Region (GR)', 4, 1);
INSERT INTO geography_types (id, label, label_singular, "order", is_available) VALUES ('macroeconomies', 'Macroeconomies (ME)', 'Macroeconomy (ME)', 5, 1);
INSERT INTO geography_types (id, label, label_singular, "order", is_available) VALUES ('northern_latitudes', 'Northern Latitudes', 'Northern Latitude', 6, 1);

-- Countries → admin0 (234 entries)
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Afghanistan', 'Afghanistan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Albania', 'Albania', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Algeria', 'Algeria', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('American Samoa', 'American Samoa', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Andorra', 'Andorra', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Angola', 'Angola', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Anguilla', 'Anguilla', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Antarctica', 'Antarctica', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Antigua and Barbuda', 'Antigua and Barbuda', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Argentina', 'Argentina', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Armenia', 'Armenia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Aruba', 'Aruba', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Australia', 'Australia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Austria', 'Austria', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Azerbaijan', 'Azerbaijan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Bahamas', 'Bahamas', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Bahrain', 'Bahrain', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Bangladesh', 'Bangladesh', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Barbados', 'Barbados', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Belarus', 'Belarus', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Belgium', 'Belgium', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Belize', 'Belize', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Benin', 'Benin', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Bermuda', 'Bermuda', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Bhutan', 'Bhutan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Bolivia', 'Bolivia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('"Bonaire', '"Bonaire', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Botswana', 'Botswana', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Bouvet Island', 'Bouvet Island', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Brazil', 'Brazil', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('British Indian Ocean Territory', 'British Indian Ocean Territory', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('British Virgin Islands', 'British Virgin Islands', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Brunei Darussalam', 'Brunei Darussalam', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Bulgaria', 'Bulgaria', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Burkina Faso', 'Burkina Faso', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Burundi', 'Burundi', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Cabo Verde', 'Cabo Verde', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Cambodia', 'Cambodia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Cameroon', 'Cameroon', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Canada', 'Canada', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Cayman Islands', 'Cayman Islands', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Central African Republic', 'Central African Republic', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Chad', 'Chad', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Chile', 'Chile', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('China', 'China', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Christmas Island', 'Christmas Island', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Colombia', 'Colombia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Comoros', 'Comoros', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Congo', 'Congo', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Cook Islands', 'Cook Islands', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Costa Rica', 'Costa Rica', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Croatia', 'Croatia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Cuba', 'Cuba', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Curaçao', 'Curaçao', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Cyprus', 'Cyprus', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Czechia', 'Czechia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Côte d''Ivoire', 'Côte d''Ivoire', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Democratic Republic of the Congo', 'Democratic Republic of the Congo', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Denmark', 'Denmark', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Djibouti', 'Djibouti', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Dominica', 'Dominica', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Dominican Republic', 'Dominican Republic', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Ecuador', 'Ecuador', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Egypt', 'Egypt', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('El Salvador', 'El Salvador', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Equatorial Guinea', 'Equatorial Guinea', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Eritrea', 'Eritrea', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Estonia', 'Estonia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Eswatini', 'Eswatini', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Ethiopia', 'Ethiopia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Falkland Islands (Malvinas)', 'Falkland Islands (Malvinas)', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Faroe Islands', 'Faroe Islands', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Fiji', 'Fiji', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Finland', 'Finland', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('France', 'France', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('French Guiana', 'French Guiana', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('French Polynesia', 'French Polynesia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('French Southern Territories', 'French Southern Territories', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Haiti', 'Haiti', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Honduras', 'Honduras', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Hong Kong', 'Hong Kong', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Hungary', 'Hungary', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Iceland', 'Iceland', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('India', 'India', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Indonesia', 'Indonesia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Iran', 'Iran', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Iraq', 'Iraq', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Ireland', 'Ireland', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Isle of Man', 'Isle of Man', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Israel', 'Israel', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Italy', 'Italy', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Jamaica', 'Jamaica', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Japan', 'Japan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Jersey', 'Jersey', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Jordan', 'Jordan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Kazakhstan', 'Kazakhstan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Kenya', 'Kenya', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Kiribati', 'Kiribati', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Kosovo', 'Kosovo', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Kuwait', 'Kuwait', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Kyrgyzstan', 'Kyrgyzstan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Laos', 'Laos', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Latvia', 'Latvia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Lebanon', 'Lebanon', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Lesotho', 'Lesotho', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Liberia', 'Liberia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Libya', 'Libya', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Liechtenstein', 'Liechtenstein', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Lithuania', 'Lithuania', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Luxembourg', 'Luxembourg', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Macao', 'Macao', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Madagascar', 'Madagascar', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Malawi', 'Malawi', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Malaysia', 'Malaysia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Maldives', 'Maldives', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Mali', 'Mali', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Malta', 'Malta', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Marshall Islands', 'Marshall Islands', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Martinique', 'Martinique', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Mauritania', 'Mauritania', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Mauritius', 'Mauritius', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Mayotte', 'Mayotte', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Mexico', 'Mexico', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Micronesia', 'Micronesia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Moldova', 'Moldova', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Monaco', 'Monaco', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Mongolia', 'Mongolia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Montenegro', 'Montenegro', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Montserrat', 'Montserrat', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Morocco', 'Morocco', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Mozambique', 'Mozambique', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Myanmar', 'Myanmar', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Namibia', 'Namibia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Nauru', 'Nauru', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Nepal', 'Nepal', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Netherlands', 'Netherlands', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('New Caledonia', 'New Caledonia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('New Zealand', 'New Zealand', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Nicaragua', 'Nicaragua', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Niger', 'Niger', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Nigeria', 'Nigeria', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Niue', 'Niue', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Norfolk Island', 'Norfolk Island', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('North Korea', 'North Korea', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('North Macedonia', 'North Macedonia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Northern Mariana Islands', 'Northern Mariana Islands', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Norway', 'Norway', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Oman', 'Oman', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Pakistan', 'Pakistan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Palau', 'Palau', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Palestine', 'Palestine', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Panama', 'Panama', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Papua New Guinea', 'Papua New Guinea', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Paraguay', 'Paraguay', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Peru', 'Peru', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Philippines', 'Philippines', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Pitcairn', 'Pitcairn', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Poland', 'Poland', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Portugal', 'Portugal', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Puerto Rico', 'Puerto Rico', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Qatar', 'Qatar', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Romania', 'Romania', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Russian Federation', 'Russian Federation', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Rwanda', 'Rwanda', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Réunion', 'Réunion', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Saint Barthélemy', 'Saint Barthélemy', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('"Saint Helena', '"Saint Helena', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Saint Kitts and Nevis', 'Saint Kitts and Nevis', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Saint Lucia', 'Saint Lucia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Saint Martin (French part)', 'Saint Martin (French part)', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Samoa', 'Samoa', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('San Marino', 'San Marino', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Sao Tome and Principe', 'Sao Tome and Principe', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Saudi Arabia', 'Saudi Arabia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Senegal', 'Senegal', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Serbia', 'Serbia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Seychelles', 'Seychelles', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Sierra Leone', 'Sierra Leone', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Singapore', 'Singapore', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Sint Maarten (Dutch part)', 'Sint Maarten (Dutch part)', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Slovakia', 'Slovakia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Slovenia', 'Slovenia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Solomon Islands', 'Solomon Islands', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Somalia', 'Somalia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('South Africa', 'South Africa', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('South Korea', 'South Korea', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('South Sudan', 'South Sudan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Spain', 'Spain', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Sri Lanka', 'Sri Lanka', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Sudan', 'Sudan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Suriname', 'Suriname', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Svalbard and Jan Mayen', 'Svalbard and Jan Mayen', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Sweden', 'Sweden', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Switzerland', 'Switzerland', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Syria', 'Syria', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Taiwan', 'Taiwan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Tajikistan', 'Tajikistan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Tanzania', 'Tanzania', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Thailand', 'Thailand', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Timor-Leste', 'Timor-Leste', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Togo', 'Togo', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Tokelau', 'Tokelau', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Tonga', 'Tonga', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Trinidad and Tobago', 'Trinidad and Tobago', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Tunisia', 'Tunisia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Turkey', 'Turkey', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Turkmenistan', 'Turkmenistan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Turks and Caicos Islands', 'Turks and Caicos Islands', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Tuvalu', 'Tuvalu', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Uganda', 'Uganda', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Ukraine', 'Ukraine', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('United Arab Emirates', 'United Arab Emirates', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('United Kingdom', 'United Kingdom', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('United States', 'United States', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('United States Virgin Islands', 'United States Virgin Islands', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Uruguay', 'Uruguay', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Uzbekistan', 'Uzbekistan', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Vanuatu', 'Vanuatu', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Vatican', 'Vatican', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Venezuela', 'Venezuela', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Viet Nam', 'Viet Nam', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Wallis and Futuna', 'Wallis and Futuna', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Western Sahara', 'Western Sahara', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Yemen', 'Yemen', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Zambia', 'Zambia', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Zimbabwe', 'Zimbabwe', 'admin0', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Åland Islands', 'Åland Islands', 'admin0', NULL);

-- Exclusive Economic Zones (EEZ) → eez (175 entries)
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Liberia (EEZ)', 'Liberia (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Myanmar (EEZ)', 'Myanmar (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Lebanon (EEZ)', 'Lebanon (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Republic of Mauritius (EEZ)', 'Republic of Mauritius (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Brunei (EEZ)', 'Brunei (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Cambodia (EEZ)', 'Cambodia (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Saint Vincent and the Grenadines (EEZ)', 'Saint Vincent and the Grenadines (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Nigeria (EEZ)', 'Nigeria (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Romania (EEZ)', 'Romania (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Indonesia (EEZ)', 'Indonesia (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Venezuela (EEZ)', 'Venezuela (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Brazil (EEZ)', 'Brazil (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Barbados (EEZ)', 'Barbados (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Greece (EEZ)', 'Greece (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Grenada (EEZ)', 'Grenada (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Philippines (EEZ)', 'Philippines (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Tanzania (EEZ)', 'Tanzania (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Sweden (EEZ)', 'Sweden (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Ukraine (EEZ)', 'Ukraine (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Angola (EEZ)', 'Angola (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Guinea (EEZ)', 'Guinea (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Bangladesh (EEZ)', 'Bangladesh (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Mauritania (EEZ)', 'Mauritania (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Vanuatu (EEZ)', 'Vanuatu (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('India (EEZ)', 'India (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Gabon (EEZ)', 'Gabon (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Phoenix Group (EEZ)', 'Phoenix Group (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Navassa Island (EEZ)', 'Navassa Island (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Thailand (EEZ)', 'Thailand (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Panama (EEZ)', 'Panama (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Estonia (EEZ)', 'Estonia (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('China (EEZ)', 'China (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Cape Verde (EEZ)', 'Cape Verde (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Pakistan (EEZ)', 'Pakistan (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Spain (EEZ)', 'Spain (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Saint Lucia (EEZ)', 'Saint Lucia (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Western Sahara (EEZ)', 'Western Sahara (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Iceland (EEZ)', 'Iceland (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Equatorial Guinea (EEZ)', 'Equatorial Guinea (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Costa Rica (EEZ)', 'Costa Rica (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Canada (EEZ)', 'Canada (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Ghana (EEZ)', 'Ghana (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Ivory Coast (EEZ)', 'Ivory Coast (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Russia (EEZ)', 'Russia (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Federal Republic of Somalia (EEZ)', 'Federal Republic of Somalia (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Bulgaria (EEZ)', 'Bulgaria (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Ecuador (EEZ)', 'Ecuador (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Colombia (EEZ)', 'Colombia (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Comores (EEZ)', 'Comores (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Republic of the Congo (EEZ)', 'Republic of the Congo (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Nauru (EEZ)', 'Nauru (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Sudan (EEZ)', 'Sudan (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Democratic Republic of the Congo (EEZ)', 'Democratic Republic of the Congo (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Algeria (EEZ)', 'Algeria (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('El Salvador (EEZ)', 'El Salvador (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Papua New Guinea (EEZ)', 'Papua New Guinea (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Marshall Islands (EEZ)', 'Marshall Islands (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Gambia (EEZ)', 'Gambia (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('South Korea (EEZ)', 'South Korea (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Sao Tome and Principe (EEZ)', 'Sao Tome and Principe (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Belize (EEZ)', 'Belize (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Micronesia (EEZ)', 'Micronesia (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Italy (EEZ)', 'Italy (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Sierra Leone (EEZ)', 'Sierra Leone (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Solomon Islands (EEZ)', 'Solomon Islands (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Dominican Republic (EEZ)', 'Dominican Republic (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Israel (EEZ)', 'Israel (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Morocco (EEZ)', 'Morocco (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Togo (EEZ)', 'Togo (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Oman (EEZ)', 'Oman (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Senegal (EEZ)', 'Senegal (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Tonga (EEZ)', 'Tonga (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Antigua and Barbuda (EEZ)', 'Antigua and Barbuda (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Malaysia (EEZ)', 'Malaysia (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Guinea-Bissau (EEZ)', 'Guinea-Bissau (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Taiwan (EEZ)', 'Taiwan (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Palau (EEZ)', 'Palau (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Suriname (EEZ)', 'Suriname (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Benin (EEZ)', 'Benin (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Eritrea (EEZ)', 'Eritrea (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Georgia (EEZ)', 'Georgia (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Ireland (EEZ)', 'Ireland (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Guyana (EEZ)', 'Guyana (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Timor Leste (EEZ)', 'Timor Leste (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Saint Kitts and Nevis (EEZ)', 'Saint Kitts and Nevis (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Samoa (EEZ)', 'Samoa (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('South Africa (EEZ)', 'South Africa (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Lithuania (EEZ)', 'Lithuania (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Trinidad and Tobago (EEZ)', 'Trinidad and Tobago (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Cuba (EEZ)', 'Cuba (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Kenya (EEZ)', 'Kenya (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Peru (EEZ)', 'Peru (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Saudi Arabia (EEZ)', 'Saudi Arabia (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Mozambique (EEZ)', 'Mozambique (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Namibia (EEZ)', 'Namibia (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Latvia (EEZ)', 'Latvia (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Dominica (EEZ)', 'Dominica (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Vietnam (EEZ)', 'Vietnam (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Tuvalu (EEZ)', 'Tuvalu (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Guatemala (EEZ)', 'Guatemala (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Fiji (EEZ)', 'Fiji (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Nicaragua (EEZ)', 'Nicaragua (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Turkey (EEZ)', 'Turkey (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Tunisia (EEZ)', 'Tunisia (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Argentina (EEZ)', 'Argentina (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Cameroon (EEZ)', 'Cameroon (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Japan (EEZ)', 'Japan (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Sri Lanka (EEZ)', 'Sri Lanka (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Maldives (EEZ)', 'Maldives (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Egypt (EEZ)', 'Egypt (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Malta (EEZ)', 'Malta (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Seychelles (EEZ)', 'Seychelles (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Germany (EEZ)', 'Germany (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Yemen (EEZ)', 'Yemen (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Madagascar (EEZ)', 'Madagascar (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Honduras (EEZ)', 'Honduras (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Jamaica (EEZ)', 'Jamaica (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Bahamas (EEZ)', 'Bahamas (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Libya (EEZ)', 'Libya (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Portugal (EEZ)', 'Portugal (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Mexico (EEZ)', 'Mexico (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Uruguay (EEZ)', 'Uruguay (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('North Korea (EEZ)', 'North Korea (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Norway (EEZ)', 'Norway (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Cyprus (EEZ)', 'Cyprus (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('French Polynesia (EEZ)', 'French Polynesia (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Mayotte (EEZ)', 'Mayotte (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Ile Tromelin (EEZ)', 'Ile Tromelin (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('New Caledonia (EEZ)', 'New Caledonia (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('La Reunion (EEZ)', 'La Reunion (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Matthew and Hunter Islands (EEZ)', 'Matthew and Hunter Islands (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Clipperton Island (EEZ)', 'Clipperton Island (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Guadeloupe (EEZ)', 'Guadeloupe (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Saint Barthelemy (EEZ)', 'Saint Barthelemy (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Collectivity of Saint Martin (EEZ)', 'Collectivity of Saint Martin (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Saint-Pierre and Miquelon (EEZ)', 'Saint-Pierre and Miquelon (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Martinique (EEZ)', 'Martinique (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('French Guiana (EEZ)', 'French Guiana (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('France (EEZ)', 'France (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Amsterdam and Saint Paul Islands (EEZ)', 'Amsterdam and Saint Paul Islands (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Falkland / Malvinas Islands (EEZ)', 'Falkland / Malvinas Islands (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Pitcairn (EEZ)', 'Pitcairn (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Anguilla (EEZ)', 'Anguilla (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('British Virgin Islands (EEZ)', 'British Virgin Islands (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Cayman Islands (EEZ)', 'Cayman Islands (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Montserrat (EEZ)', 'Montserrat (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Turks and Caicos Islands (EEZ)', 'Turks and Caicos Islands (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('South Georgia and the South Sandwich Islands (EEZ)', 'South Georgia and the South Sandwich Islands (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Bermuda (EEZ)', 'Bermuda (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('United Kingdom (EEZ)', 'United Kingdom (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('St Helene, Ascension and Tristan da Cunha (EEZ)', 'St Helene, Ascension and Tristan da Cunha (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('American Samoa (EEZ)', 'American Samoa (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('United States Virgin Islands (EEZ)', 'United States Virgin Islands (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Guam (EEZ)', 'Guam (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Northern Mariana Islands (EEZ)', 'Northern Mariana Islands (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Hawaii (EEZ)', 'Hawaii (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Alaska (EEZ)', 'Alaska (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('United States (EEZ)', 'United States (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Palmyra Atoll (EEZ)', 'Palmyra Atoll (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Puerto Rico (EEZ)', 'Puerto Rico (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Netherland (EEZ)', 'Netherland (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Caribbean Netherlands (EEZ)', 'Caribbean Netherlands (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Cook Islands (EEZ)', 'Cook Islands (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('New Zealand (EEZ)', 'New Zealand (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Chile (EEZ)', 'Chile (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Easter Islands (EEZ)', 'Easter Islands (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('San Felix and San Ambrosia islands (EEZ)', 'San Felix and San Ambrosia islands (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Australia (EEZ)', 'Australia (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Macquire Island (EEZ)', 'Macquire Island (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Norfolk Island (EEZ)', 'Norfolk Island (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Heard and McDonald Islands (EEZ)', 'Heard and McDonald Islands (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Cocos Islands (EEZ)', 'Cocos Islands (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Christmas Islands (EEZ)', 'Christmas Islands (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Denmark (EEZ)', 'Denmark (EEZ)', 'eez', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Greenland (EEZ)', 'Greenland (EEZ)', 'eez', NULL);

-- Cities → cities (144 entries)
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Accra', 'Accra', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Addis Abeba', 'Addis Abeba', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Alicante', 'Alicante', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Amman', 'Amman', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Amsterdam', 'Amsterdam', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Antwerp', 'Antwerp', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Athens', 'Athens', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Auckland', 'Auckland', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Barcelona', 'Barcelona', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Bari', 'Bari', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Basel', 'Basel', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Belgrade', 'Belgrade', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Berlin', 'Berlin', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Bilbao', 'Bilbao', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Birmingham', 'Birmingham', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Bodø', 'Bodø', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Bogota', 'Bogota', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Bologna', 'Bologna', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Bordeaux', 'Bordeaux', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Brasov', 'Brasov', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Bratislava', 'Bratislava', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Brussels', 'Brussels', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Bucharest', 'Bucharest', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Budapest', 'Budapest', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Buenos Aires', 'Buenos Aires', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Cairo', 'Cairo', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Cape Town', 'Cape Town', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Charleroi', 'Charleroi', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Chennai', 'Chennai', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Cluj Napoca', 'Cluj Napoca', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Cologne', 'Cologne', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Copenhagen', 'Copenhagen', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Curitiba', 'Curitiba', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Dakar', 'Dakar', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Debrecen', 'Debrecen', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Dhaka', 'Dhaka', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Dubai', 'Dubai', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Dublin', 'Dublin', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Dusseldorf', 'Dusseldorf', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Edinburgh', 'Edinburgh', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Frankfurt am Main', 'Frankfurt am Main', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Gdansk', 'Gdansk', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Geneva', 'Geneva', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Genoa', 'Genoa', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Ghent', 'Ghent', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Glasgow', 'Glasgow', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Goteborg', 'Goteborg', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Graz', 'Graz', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Gyor', 'Gyor', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Hamburg', 'Hamburg', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Helsinki', 'Helsinki', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Ho Chi Minh', 'Ho Chi Minh', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Hong Kong', 'Hong Kong', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Houston', 'Houston', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Istanbul', 'Istanbul', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Islamabad', 'Islamabad', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Jakarta', 'Jakarta', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Karachi', 'Karachi', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Klaipeda', 'Klaipeda', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Kosice', 'Kosice', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Krakow', 'Krakow', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Lagos', 'Lagos', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Leeds', 'Leeds', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Leipzig', 'Leipzig', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Liege', 'Liege', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Lille', 'Lille', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Lima', 'Lima', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Lisbon', 'Lisbon', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Ljubljana', 'Ljubljana', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Lodz', 'Lodz', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('London', 'London', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Los Angeles', 'Los Angeles', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Luxembourg', 'Luxembourg', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Lyon', 'Lyon', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Madrid', 'Madrid', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Malaga', 'Malaga', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Marrakesh', 'Marrakesh', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Marseille', 'Marseille', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Medina', 'Medina', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Melbourne', 'Melbourne', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Mexico City', 'Mexico City', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Milan', 'Milan', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Miskolc', 'Miskolc', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Mogadishu', 'Mogadishu', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Montpellier', 'Montpellier', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Moscow', 'Moscow', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Munich', 'Munich', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Murcia', 'Murcia', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Nairobi', 'Nairobi', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Nanjing', 'Nanjing', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Nantes', 'Nantes', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Naples', 'Naples', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Nassau', 'Nassau', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('New York', 'New York', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Newcastle', 'Newcastle', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Nice', 'Nice', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Novi Sad', 'Novi Sad', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Oslo', 'Oslo', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Padua', 'Padua', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Palermo', 'Palermo', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Palma de Mallorca', 'Palma de Mallorca', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Paris', 'Paris', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Pecs', 'Pecs', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Phoenix', 'Phoenix', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Podgorica', 'Podgorica', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Porto', 'Porto', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Prague', 'Prague', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Rabat', 'Rabat', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Reykjavik', 'Reykjavik', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Riga', 'Riga', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Rome', 'Rome', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Rotterdam', 'Rotterdam', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Salvador', 'Salvador', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Santiago', 'Santiago', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Sarajevo', 'Sarajevo', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Sevilla', 'Sevilla', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Singapore', 'Singapore', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Skopje', 'Skopje', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Sofia', 'Sofia', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Split', 'Split', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Stockholm', 'Stockholm', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Strasbourg', 'Strasbourg', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Sydney', 'Sydney', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Szeged', 'Szeged', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Tallinn', 'Tallinn', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Tartu', 'Tartu', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Teheran', 'Teheran', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Thessaloniki', 'Thessaloniki', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Tirana', 'Tirana', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Tokyo', 'Tokyo', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Toronto', 'Toronto', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Toulouse', 'Toulouse', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Trieste', 'Trieste', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Tschwane', 'Tschwane', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Turin', 'Turin', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Utrecht', 'Utrecht', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Valencia', 'Valencia', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Varna', 'Varna', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Vienna', 'Vienna', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Vilnius', 'Vilnius', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Warsaw', 'Warsaw', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Wroclaw', 'Wroclaw', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Zagreb', 'Zagreb', 'cities', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Zurich', 'Zurich', 'cities', NULL);

-- River Basins (RB) → river_basins (75 entries)
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Indigirka (RB)', 'Indigirka (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Ob (RB)', 'Ob (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Brahmaputra (RB)', 'Brahmaputra (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Ganges (RB)', 'Ganges (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Indus (RB)', 'Indus (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Irrawaddy (RB)', 'Irrawaddy (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Salween (RB)', 'Salween (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Kamchatka (RB)', 'Kamchatka (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Mekong (RB)', 'Mekong (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Yangtze (RB)', 'Yangtze (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Yellow River (RB)', 'Yellow River (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Aral Sea (RB)', 'Aral Sea (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Chuy (RB)', 'Chuy (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Har Us Nuur (RB)', 'Har Us Nuur (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Lake Balkhash (RB)', 'Lake Balkhash (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Talas (RB)', 'Talas (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Tarim He (RB)', 'Tarim He (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Uvs Nuur (RB)', 'Uvs Nuur (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Ysyk Kol (RB)', 'Ysyk Kol (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Amazon (RB)', 'Amazon (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Chico (RB)', 'Chico (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Colorado (RB)', 'Colorado (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Magdalena (RB)', 'Magdalena (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Negro (RB)', 'Negro (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Santa Cruz (RB)', 'Santa Cruz (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Aisen (RB)', 'Aisen (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Azopardo (RB)', 'Azopardo (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Baker (RB)', 'Baker (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Biobio (RB)', 'Biobio (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Cisnes (RB)', 'Cisnes (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Copiapo (RB)', 'Copiapo (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Huasco (RB)', 'Huasco (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Majes (RB)', 'Majes (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Ocona (RB)', 'Ocona (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Palena (RB)', 'Palena (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Pascua (RB)', 'Pascua (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Puelo (RB)', 'Puelo (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Rapel (RB)', 'Rapel (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Santa (RB)', 'Santa (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Serrano (RB)', 'Serrano (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Valdivia (RB)', 'Valdivia (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Yelcho (RB)', 'Yelcho (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Titicaca (RB)', 'Titicaca (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Colville (RB)', 'Colville (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Mackenzie (RB)', 'Mackenzie (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Nelson (RB)', 'Nelson (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Alsek (RB)', 'Alsek (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Columbia (RB)', 'Columbia (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Copper (RB)', 'Copper (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Fraser (RB)', 'Fraser (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Kuskokwim (RB)', 'Kuskokwim (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Nass (RB)', 'Nass (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Nushagak (RB)', 'Nushagak (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Skagit (RB)', 'Skagit (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Skeena (RB)', 'Skeena (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Stikine (RB)', 'Stikine (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Susitna (RB)', 'Susitna (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Taku (RB)', 'Taku (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Yukon (RB)', 'Yukon (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Clutha (RB)', 'Clutha (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Jokulsa a Fjollum (RB)', 'Jokulsa a Fjollum (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Lagarfljot (RB)', 'Lagarfljot (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Svarta (RB)', 'Svarta (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Danube (RB)', 'Danube (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Dramselva (RB)', 'Dramselva (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Glomaa (RB)', 'Glomaa (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Kalixalven (RB)', 'Kalixalven (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Kuban (RB)', 'Kuban (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Lulealven (RB)', 'Lulealven (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Olfusa (RB)', 'Olfusa (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Po (RB)', 'Po (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Rhine (RB)', 'Rhine (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Rhone (RB)', 'Rhone (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Thjorsa (RB)', 'Thjorsa (RB)', 'river_basins', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Tornealven (RB)', 'Tornealven (RB)', 'river_basins', NULL);

-- Glacier Regions (GR) → glacier_regions (13 entries)
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Arctic Canada (GR)', 'Arctic Canada (GR)', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Caucasus and Middle East (GR)', 'Caucasus and Middle East (GR)', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Central Asia (GR)', 'Central Asia (GR)', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Central Europe (GR)', 'Central Europe (GR)', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('East Asia (GR)', 'East Asia (GR)', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Greenland Periphery (GR)', 'Greenland Periphery (GR)', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('New Zealand (GR)', 'New Zealand (GR)', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Northern Andes (GR)', 'Northern Andes (GR)', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Scandinavia and Iceland (GR)', 'Scandinavia and Iceland (GR)', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Southern Andes (GR)', 'Southern Andes (GR)', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Subantarctic and Antarctic Islands (GR)', 'Subantarctic and Antarctic Islands (GR)', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Svalbard, Jan Mayen and Russian Arctic (GR)', 'Svalbard, Jan Mayen and Russian Arctic (GR)', 'glacier_regions', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Western Canada and USA (GR)', 'Western Canada and USA (GR)', 'glacier_regions', NULL);

-- Macroeconomies (ME) → macroeconomies (14 entries)
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Central Africa (ME)', 'Central Africa (ME)', 'macroeconomies', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('East Africa (ME)', 'East Africa (ME)', 'macroeconomies', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('East Asia (ME)', 'East Asia (ME)', 'macroeconomies', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Europe (ME)', 'Europe (ME)', 'macroeconomies', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('North Africa (ME)', 'North Africa (ME)', 'macroeconomies', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('North America (ME)', 'North America (ME)', 'macroeconomies', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Oceania (ME)', 'Oceania (ME)', 'macroeconomies', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Former Soviet Union (ME)', 'Former Soviet Union (ME)', 'macroeconomies', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('South Africa (ME)', 'South Africa (ME)', 'macroeconomies', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('South America (ME)', 'South America (ME)', 'macroeconomies', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('South Asia (ME)', 'South Asia (ME)', 'macroeconomies', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('South East Asia (ME)', 'South East Asia (ME)', 'macroeconomies', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('West Africa (ME)', 'West Africa (ME)', 'macroeconomies', NULL);
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('West Asia (ME)', 'West Asia (ME)', 'macroeconomies', NULL);

-- Northern Latitudes → northern_latitudes (1 entries)
INSERT INTO geographies (id, label, geography_type, parent_id) VALUES ('Northern Latitudes', 'Northern Latitudes', 'northern_latitudes', NULL);
