// Generated from the IIASA geographies reference (geos.csv, "Country" rows).
// Maps a catalog country label to its ISO 3166-1 alpha-3 code, used as the
// geographies.geo_id that links a country to its map geo-shape and flag asset.
// The catalog truncates two ids in the source YAML to "Bonaire" / "Saint
// Helena", so those short labels are aliased here to the full territory's ISO3.

export const countryIso3: Record<string, string> = {
  Bonaire: 'BES', // catalog short id for "Bonaire, Sint Eustatius and Saba"
  'Saint Helena': 'SHN', // catalog short id for "Saint Helena, Ascension and Tristan da Cunha"
  Afghanistan: 'AFG',
  "Åland Islands": 'ALA',
  Albania: 'ALB',
  Algeria: 'DZA',
  "American Samoa": 'ASM',
  Andorra: 'AND',
  Angola: 'AGO',
  Anguilla: 'AIA',
  Antarctica: 'ATA',
  "Antigua and Barbuda": 'ATG',
  Argentina: 'ARG',
  Armenia: 'ARM',
  Aruba: 'ABW',
  Australia: 'AUS',
  Austria: 'AUT',
  Azerbaijan: 'AZE',
  Bahamas: 'BHS',
  Bahrain: 'BHR',
  Bangladesh: 'BGD',
  Barbados: 'BRB',
  Belarus: 'BLR',
  Belgium: 'BEL',
  Belize: 'BLZ',
  Benin: 'BEN',
  Bermuda: 'BMU',
  Bhutan: 'BTN',
  Bolivia: 'BOL',
  "Bonaire, Sint Eustatius and Saba": 'BES',
  "Bosnia and Herzegovina": 'BIH',
  Botswana: 'BWA',
  "Bouvet Island": 'BVT',
  Brazil: 'BRA',
  "British Indian Ocean Territory": 'IOT',
  "British Virgin Islands": 'VGB',
  "Brunei Darussalam": 'BRN',
  Bulgaria: 'BGR',
  "Burkina Faso": 'BFA',
  Burundi: 'BDI',
  "Cabo Verde": 'CPV',
  Cambodia: 'KHM',
  Cameroon: 'CMR',
  Canada: 'CAN',
  "Cayman Islands": 'CYM',
  "Central African Republic": 'CAF',
  Chad: 'TCD',
  Chile: 'CHL',
  China: 'CHN',
  "Christmas Island": 'CXR',
  "Cocos (Keeling) Islands": 'CCK',
  Colombia: 'COL',
  Comoros: 'COM',
  Congo: 'COG',
  "Cook Islands": 'COK',
  "Costa Rica": 'CRI',
  "Côte d'Ivoire": 'CIV',
  Croatia: 'HRV',
  Cuba: 'CUB',
  "Curaçao": 'CUW',
  Cyprus: 'CYP',
  Czechia: 'CZE',
  "Democratic Republic of the Congo": 'COD',
  Denmark: 'DNK',
  Djibouti: 'DJI',
  Dominica: 'DMA',
  "Dominican Republic": 'DOM',
  Ecuador: 'ECU',
  Egypt: 'EGY',
  "El Salvador": 'SLV',
  "Equatorial Guinea": 'GNQ',
  Eritrea: 'ERI',
  Estonia: 'EST',
  Eswatini: 'SWZ',
  Ethiopia: 'ETH',
  "Falkland Islands (Malvinas)": 'FLK',
  "Faroe Islands": 'FRO',
  Fiji: 'FJI',
  Finland: 'FIN',
  France: 'FRA',
  "French Guiana": 'GUF',
  "French Polynesia": 'PYF',
  "French Southern Territories": 'ATF',
  // The "G" countries are absent from the source reference (a gap in the export);
  // added here from the live map shapes so they link and appear in the catalog.
  Gabon: 'GAB',
  Gambia: 'GMB',
  Georgia: 'GEO',
  Germany: 'DEU',
  Ghana: 'GHA',
  Greece: 'GRC',
  Greenland: 'GRL',
  Guatemala: 'GTM',
  Guinea: 'GIN',
  "Guinea-Bissau": 'GNB',
  Guyana: 'GUY',
  Haiti: 'HTI',
  "Heard Island and McDonald Islands": 'HMD',
  Honduras: 'HND',
  "Hong Kong": 'HKG',
  Hungary: 'HUN',
  Iceland: 'ISL',
  India: 'IND',
  Indonesia: 'IDN',
  Iran: 'IRN',
  Iraq: 'IRQ',
  Ireland: 'IRL',
  "Isle of Man": 'IMN',
  Israel: 'ISR',
  Italy: 'ITA',
  Jamaica: 'JAM',
  Japan: 'JPN',
  Jersey: 'JEY',
  Jordan: 'JOR',
  Kazakhstan: 'KAZ',
  Kenya: 'KEN',
  Kiribati: 'KIR',
  Kosovo: 'KOS',
  Kuwait: 'KWT',
  Kyrgyzstan: 'KGZ',
  Laos: 'LAO',
  Latvia: 'LVA',
  Lebanon: 'LBN',
  Lesotho: 'LSO',
  Liberia: 'LBR',
  Libya: 'LBY',
  Liechtenstein: 'LIE',
  Lithuania: 'LTU',
  Luxembourg: 'LUX',
  Macao: 'MAC',
  Madagascar: 'MDG',
  Malawi: 'MWI',
  Malaysia: 'MYS',
  Maldives: 'MDV',
  Mali: 'MLI',
  Malta: 'MLT',
  "Marshall Islands": 'MHL',
  Martinique: 'MTQ',
  Mauritania: 'MRT',
  Mauritius: 'MUS',
  Mayotte: 'MYT',
  Mexico: 'MEX',
  Micronesia: 'FSM',
  Moldova: 'MDA',
  Monaco: 'MCO',
  Mongolia: 'MNG',
  Montenegro: 'MNE',
  Montserrat: 'MSR',
  Morocco: 'MAR',
  Mozambique: 'MOZ',
  Myanmar: 'MMR',
  Namibia: 'NAM',
  Nauru: 'NRU',
  Nepal: 'NPL',
  Netherlands: 'NLD',
  "New Caledonia": 'NCL',
  "New Zealand": 'NZL',
  Nicaragua: 'NIC',
  Niger: 'NER',
  Nigeria: 'NGA',
  Niue: 'NIU',
  "Norfolk Island": 'NFK',
  "North Korea": 'PRK',
  "North Macedonia": 'MKD',
  "Northern Mariana Islands": 'MNP',
  Norway: 'NOR',
  Oman: 'OMN',
  Pakistan: 'PAK',
  Palau: 'PLW',
  Palestine: 'PSE',
  Panama: 'PAN',
  "Papua New Guinea": 'PNG',
  Paraguay: 'PRY',
  Peru: 'PER',
  Philippines: 'PHL',
  Pitcairn: 'PCN',
  Poland: 'POL',
  Portugal: 'PRT',
  "Puerto Rico": 'PRI',
  Qatar: 'QAT',
  "Réunion": 'REU',
  Romania: 'ROU',
  "Russian Federation": 'RUS',
  Rwanda: 'RWA',
  "Saint Barthélemy": 'BLM',
  "Saint Helena, Ascension and Tristan da Cunha": 'SHN',
  "Saint Kitts and Nevis": 'KNA',
  "Saint Lucia": 'LCA',
  "Saint Martin (French part)": 'MAF',
  "Saint Pierre and Miquelon": 'SPM',
  "Saint Vincent and the Grenadines": 'VCT',
  Samoa: 'WSM',
  "San Marino": 'SMR',
  "Sao Tome and Principe": 'STP',
  "Saudi Arabia": 'SAU',
  Senegal: 'SEN',
  Serbia: 'SRB',
  Seychelles: 'SYC',
  "Sierra Leone": 'SLE',
  Singapore: 'SGP',
  "Sint Maarten (Dutch part)": 'SXM',
  Slovakia: 'SVK',
  Slovenia: 'SVN',
  "Solomon Islands": 'SLB',
  Somalia: 'SOM',
  "South Africa": 'ZAF',
  "South Georgia and the South Sandwich Islands": 'SGS',
  "South Korea": 'KOR',
  "South Sudan": 'SSD',
  Spain: 'ESP',
  "Sri Lanka": 'LKA',
  Sudan: 'SDN',
  Suriname: 'SUR',
  "Svalbard and Jan Mayen": 'SJM',
  Sweden: 'SWE',
  Switzerland: 'CHE',
  Syria: 'SYR',
  Taiwan: 'TWN',
  Tajikistan: 'TJK',
  Tanzania: 'TZA',
  Thailand: 'THA',
  "Timor-Leste": 'TLS',
  Togo: 'TGO',
  Tokelau: 'TKL',
  Tonga: 'TON',
  "Trinidad and Tobago": 'TTO',
  Tunisia: 'TUN',
  Turkey: 'TUR',
  Turkmenistan: 'TKM',
  "Turks and Caicos Islands": 'TCA',
  Tuvalu: 'TUV',
  Uganda: 'UGA',
  Ukraine: 'UKR',
  "United Arab Emirates": 'ARE',
  "United Kingdom": 'GBR',
  "United States": 'USA',
  "United States Minor Outlying Islands": 'UMI',
  "United States Virgin Islands": 'VIR',
  Uruguay: 'URY',
  Uzbekistan: 'UZB',
  Vanuatu: 'VUT',
  Vatican: 'VAT',
  Venezuela: 'VEN',
  "Viet Nam": 'VNM',
  "Wallis and Futuna": 'WLF',
  "Western Sahara": 'ESH',
  Yemen: 'YEM',
  Zambia: 'ZMB',
  Zimbabwe: 'ZWE',
};
