/**
 * Hand-authored geography hierarchy. Edges here are compiled into the
 * `geography_parents` seed by import-geographies.ts. Child keys (countries,
 * cities, river basins, EEZ) must exactly match a geography id in
 * geographies.yaml — the importer throws on an unknown child. Parent country
 * references that don't exist in the seed (the YAML is missing all "G"
 * countries, e.g. Germany/Greece/Ghana) are skipped with a warning rather than
 * failing the build, so those children simply have no parent edge.
 *
 * Two country ids are truncated in the source YAML and carry a leading double
 * quote (`"Bonaire`, `"Saint Helena`); they are reproduced verbatim here.
 */

// Ordered for display. These also become `continent` geographies.
export const continents: string[] = [
  'Africa',
  'Asia',
  'Europe',
  'North America',
  'South America',
  'Oceania',
  'Antarctica',
];

// Every country in geographies.yaml -> its continent.
export const countryContinent: Record<string, string> = {
  Afghanistan: 'Asia',
  Albania: 'Europe',
  Algeria: 'Africa',
  'American Samoa': 'Oceania',
  Andorra: 'Europe',
  Angola: 'Africa',
  Anguilla: 'North America',
  Antarctica: 'Antarctica',
  'Antigua and Barbuda': 'North America',
  Argentina: 'South America',
  Armenia: 'Asia',
  Aruba: 'North America',
  Australia: 'Oceania',
  Austria: 'Europe',
  Azerbaijan: 'Asia',
  Bahamas: 'North America',
  Bahrain: 'Asia',
  Bangladesh: 'Asia',
  Barbados: 'North America',
  Belarus: 'Europe',
  Belgium: 'Europe',
  Belize: 'North America',
  Benin: 'Africa',
  Bermuda: 'North America',
  Bhutan: 'Asia',
  Bolivia: 'South America',
  Bonaire: 'North America',
  'Bosnia and Herzegovina': 'Europe',
  Botswana: 'Africa',
  'Bouvet Island': 'Antarctica',
  Brazil: 'South America',
  'British Indian Ocean Territory': 'Asia',
  'British Virgin Islands': 'North America',
  'Brunei Darussalam': 'Asia',
  Bulgaria: 'Europe',
  'Burkina Faso': 'Africa',
  Burundi: 'Africa',
  'Cabo Verde': 'Africa',
  Cambodia: 'Asia',
  Cameroon: 'Africa',
  Canada: 'North America',
  'Cayman Islands': 'North America',
  'Central African Republic': 'Africa',
  Chad: 'Africa',
  Chile: 'South America',
  China: 'Asia',
  'Christmas Island': 'Asia',
  'Cocos (Keeling) Islands': 'Asia',
  Colombia: 'South America',
  Comoros: 'Africa',
  Congo: 'Africa',
  'Cook Islands': 'Oceania',
  'Costa Rica': 'North America',
  Croatia: 'Europe',
  Cuba: 'North America',
  'Curaçao': 'North America',
  Cyprus: 'Europe',
  Czechia: 'Europe',
  "Côte d'Ivoire": 'Africa',
  'Democratic Republic of the Congo': 'Africa',
  Denmark: 'Europe',
  Djibouti: 'Africa',
  Dominica: 'North America',
  'Dominican Republic': 'North America',
  Ecuador: 'South America',
  Egypt: 'Africa',
  'El Salvador': 'North America',
  'Equatorial Guinea': 'Africa',
  Eritrea: 'Africa',
  Estonia: 'Europe',
  Eswatini: 'Africa',
  Ethiopia: 'Africa',
  'Falkland Islands (Malvinas)': 'South America',
  'Faroe Islands': 'Europe',
  Fiji: 'Oceania',
  Finland: 'Europe',
  France: 'Europe',
  'French Guiana': 'South America',
  'French Polynesia': 'Oceania',
  'French Southern Territories': 'Antarctica',
  Gabon: 'Africa',
  Gambia: 'Africa',
  Georgia: 'Asia',
  Germany: 'Europe',
  Ghana: 'Africa',
  Greece: 'Europe',
  Greenland: 'North America',
  Guatemala: 'North America',
  Guinea: 'Africa',
  'Guinea-Bissau': 'Africa',
  Guyana: 'South America',
  Haiti: 'North America',
  'Heard Island and McDonald Islands': 'Antarctica',
  Honduras: 'North America',
  'Hong Kong': 'Asia',
  Hungary: 'Europe',
  Iceland: 'Europe',
  India: 'Asia',
  Indonesia: 'Asia',
  Iran: 'Asia',
  Iraq: 'Asia',
  Ireland: 'Europe',
  'Isle of Man': 'Europe',
  Israel: 'Asia',
  Italy: 'Europe',
  Jamaica: 'North America',
  Japan: 'Asia',
  Jersey: 'Europe',
  Jordan: 'Asia',
  Kazakhstan: 'Asia',
  Kenya: 'Africa',
  Kiribati: 'Oceania',
  Kosovo: 'Europe',
  Kuwait: 'Asia',
  Kyrgyzstan: 'Asia',
  Laos: 'Asia',
  Latvia: 'Europe',
  Lebanon: 'Asia',
  Lesotho: 'Africa',
  Liberia: 'Africa',
  Libya: 'Africa',
  Liechtenstein: 'Europe',
  Lithuania: 'Europe',
  Luxembourg: 'Europe',
  Macao: 'Asia',
  Madagascar: 'Africa',
  Malawi: 'Africa',
  Malaysia: 'Asia',
  Maldives: 'Asia',
  Mali: 'Africa',
  Malta: 'Europe',
  'Marshall Islands': 'Oceania',
  Martinique: 'North America',
  Mauritania: 'Africa',
  Mauritius: 'Africa',
  Mayotte: 'Africa',
  Mexico: 'North America',
  Micronesia: 'Oceania',
  Moldova: 'Europe',
  Monaco: 'Europe',
  Mongolia: 'Asia',
  Montenegro: 'Europe',
  Montserrat: 'North America',
  Morocco: 'Africa',
  Mozambique: 'Africa',
  Myanmar: 'Asia',
  Namibia: 'Africa',
  Nauru: 'Oceania',
  Nepal: 'Asia',
  Netherlands: 'Europe',
  'New Caledonia': 'Oceania',
  'New Zealand': 'Oceania',
  Nicaragua: 'North America',
  Niger: 'Africa',
  Nigeria: 'Africa',
  Niue: 'Oceania',
  'Norfolk Island': 'Oceania',
  'North Korea': 'Asia',
  'North Macedonia': 'Europe',
  'Northern Mariana Islands': 'Oceania',
  Norway: 'Europe',
  Oman: 'Asia',
  Pakistan: 'Asia',
  Palau: 'Oceania',
  Palestine: 'Asia',
  Panama: 'North America',
  'Papua New Guinea': 'Oceania',
  Paraguay: 'South America',
  Peru: 'South America',
  Philippines: 'Asia',
  Pitcairn: 'Oceania',
  Poland: 'Europe',
  Portugal: 'Europe',
  'Puerto Rico': 'North America',
  Qatar: 'Asia',
  Romania: 'Europe',
  'Russian Federation': 'Europe',
  Rwanda: 'Africa',
  'Réunion': 'Africa',
  'Saint Barthélemy': 'North America',
  'Saint Helena': 'Africa',
  'Saint Kitts and Nevis': 'North America',
  'Saint Lucia': 'North America',
  'Saint Martin (French part)': 'North America',
  'Saint Pierre and Miquelon': 'North America',
  'Saint Vincent and the Grenadines': 'North America',
  Samoa: 'Oceania',
  'San Marino': 'Europe',
  'Sao Tome and Principe': 'Africa',
  'Saudi Arabia': 'Asia',
  Senegal: 'Africa',
  Serbia: 'Europe',
  Seychelles: 'Africa',
  'Sierra Leone': 'Africa',
  Singapore: 'Asia',
  'Sint Maarten (Dutch part)': 'North America',
  Slovakia: 'Europe',
  Slovenia: 'Europe',
  'Solomon Islands': 'Oceania',
  Somalia: 'Africa',
  'South Africa': 'Africa',
  'South Georgia and the South Sandwich Islands': 'Antarctica',
  'South Korea': 'Asia',
  'South Sudan': 'Africa',
  Spain: 'Europe',
  'Sri Lanka': 'Asia',
  Sudan: 'Africa',
  Suriname: 'South America',
  'Svalbard and Jan Mayen': 'Europe',
  Sweden: 'Europe',
  Switzerland: 'Europe',
  Syria: 'Asia',
  Taiwan: 'Asia',
  Tajikistan: 'Asia',
  Tanzania: 'Africa',
  Thailand: 'Asia',
  'Timor-Leste': 'Asia',
  Togo: 'Africa',
  Tokelau: 'Oceania',
  Tonga: 'Oceania',
  'Trinidad and Tobago': 'North America',
  Tunisia: 'Africa',
  Turkey: 'Asia',
  Turkmenistan: 'Asia',
  'Turks and Caicos Islands': 'North America',
  Tuvalu: 'Oceania',
  Uganda: 'Africa',
  Ukraine: 'Europe',
  'United Arab Emirates': 'Asia',
  'United Kingdom': 'Europe',
  'United States': 'North America',
  'United States Minor Outlying Islands': 'Oceania',
  'United States Virgin Islands': 'North America',
  Uruguay: 'South America',
  Uzbekistan: 'Asia',
  Vanuatu: 'Oceania',
  Vatican: 'Europe',
  Venezuela: 'South America',
  'Viet Nam': 'Asia',
  'Wallis and Futuna': 'Oceania',
  'Western Sahara': 'Africa',
  Yemen: 'Asia',
  Zambia: 'Africa',
  Zimbabwe: 'Africa',
  'Åland Islands': 'Europe',
};

// Every city in geographies.yaml -> its country. Cities whose country is
// missing from the YAML (Germany, Greece, Ghana) keep the real country name;
// the edge is skipped at build time because the parent does not exist.
export const cityCountry: Record<string, string> = {
  Accra: 'Ghana',
  'Addis Abeba': 'Ethiopia',
  Alicante: 'Spain',
  Amman: 'Jordan',
  Amsterdam: 'Netherlands',
  Antwerp: 'Belgium',
  Athens: 'Greece',
  Auckland: 'New Zealand',
  Barcelona: 'Spain',
  Bari: 'Italy',
  Basel: 'Switzerland',
  Belgrade: 'Serbia',
  Berlin: 'Germany',
  Bilbao: 'Spain',
  Birmingham: 'United Kingdom',
  'Bodø': 'Norway',
  Bogota: 'Colombia',
  Bologna: 'Italy',
  Bordeaux: 'France',
  Brasov: 'Romania',
  Bratislava: 'Slovakia',
  Brussels: 'Belgium',
  Bucharest: 'Romania',
  Budapest: 'Hungary',
  'Buenos Aires': 'Argentina',
  Cairo: 'Egypt',
  'Cape Town': 'South Africa',
  Charleroi: 'Belgium',
  Chennai: 'India',
  'Cluj Napoca': 'Romania',
  Cologne: 'Germany',
  Copenhagen: 'Denmark',
  Curitiba: 'Brazil',
  Dakar: 'Senegal',
  Debrecen: 'Hungary',
  Dhaka: 'Bangladesh',
  Dubai: 'United Arab Emirates',
  Dublin: 'Ireland',
  Dusseldorf: 'Germany',
  Edinburgh: 'United Kingdom',
  'Frankfurt am Main': 'Germany',
  Gdansk: 'Poland',
  Geneva: 'Switzerland',
  Genoa: 'Italy',
  Ghent: 'Belgium',
  Glasgow: 'United Kingdom',
  Goteborg: 'Sweden',
  Graz: 'Austria',
  Gyor: 'Hungary',
  Hamburg: 'Germany',
  Helsinki: 'Finland',
  'Ho Chi Minh': 'Viet Nam',
  'Hong Kong': 'Hong Kong',
  Houston: 'United States',
  Istanbul: 'Turkey',
  Islamabad: 'Pakistan',
  Jakarta: 'Indonesia',
  Karachi: 'Pakistan',
  Klaipeda: 'Lithuania',
  Kosice: 'Slovakia',
  Krakow: 'Poland',
  Lagos: 'Nigeria',
  Leeds: 'United Kingdom',
  Leipzig: 'Germany',
  Liege: 'Belgium',
  Lille: 'France',
  Lima: 'Peru',
  Lisbon: 'Portugal',
  Ljubljana: 'Slovenia',
  Lodz: 'Poland',
  London: 'United Kingdom',
  'Los Angeles': 'United States',
  Luxembourg: 'Luxembourg',
  Lyon: 'France',
  Madrid: 'Spain',
  Malaga: 'Spain',
  Marrakesh: 'Morocco',
  Marseille: 'France',
  Medina: 'Saudi Arabia',
  Melbourne: 'Australia',
  'Mexico City': 'Mexico',
  Milan: 'Italy',
  Miskolc: 'Hungary',
  Mogadishu: 'Somalia',
  Montpellier: 'France',
  Moscow: 'Russian Federation',
  Munich: 'Germany',
  Murcia: 'Spain',
  Nairobi: 'Kenya',
  Nanjing: 'China',
  Nantes: 'France',
  Naples: 'Italy',
  Nassau: 'Bahamas',
  'New York': 'United States',
  Newcastle: 'United Kingdom',
  Nice: 'France',
  'Novi Sad': 'Serbia',
  Oslo: 'Norway',
  Padua: 'Italy',
  Palermo: 'Italy',
  'Palma de Mallorca': 'Spain',
  Paris: 'France',
  Pecs: 'Hungary',
  Phoenix: 'United States',
  Podgorica: 'Montenegro',
  Porto: 'Portugal',
  Prague: 'Czechia',
  Rabat: 'Morocco',
  Reykjavik: 'Iceland',
  Riga: 'Latvia',
  Rome: 'Italy',
  Rotterdam: 'Netherlands',
  Salvador: 'Brazil',
  Santiago: 'Chile',
  Sarajevo: 'Bosnia and Herzegovina',
  Sevilla: 'Spain',
  Singapore: 'Singapore',
  Skopje: 'North Macedonia',
  Sofia: 'Bulgaria',
  Split: 'Croatia',
  Stockholm: 'Sweden',
  Strasbourg: 'France',
  Sydney: 'Australia',
  Szeged: 'Hungary',
  Tallinn: 'Estonia',
  Tartu: 'Estonia',
  Teheran: 'Iran',
  Thessaloniki: 'Greece',
  Tirana: 'Albania',
  Tokyo: 'Japan',
  Toronto: 'Canada',
  Toulouse: 'France',
  Trieste: 'Italy',
  Tschwane: 'South Africa',
  Turin: 'Italy',
  Utrecht: 'Netherlands',
  Valencia: 'Spain',
  Varna: 'Bulgaria',
  Vienna: 'Austria',
  Vilnius: 'Lithuania',
  Warsaw: 'Poland',
  Wroclaw: 'Poland',
  Zagreb: 'Croatia',
  Zurich: 'Switzerland',
};

// EEZ exceptions only: zones whose country cannot be recovered by stripping
// " (EEZ)" from the name (alternate country spellings, territories, shared
// zones). Plain EEZ such as "France (EEZ)" -> "France" are derived in the
// importer. EEZ for missing "G" countries (Greece, Ghana, …) intentionally
// have no entry and get no edge.
export const eezCountry: Record<string, string[]> = {
  'Republic of Mauritius (EEZ)': ['Mauritius'],
  'Brunei (EEZ)': ['Brunei Darussalam'],
  'Phoenix Group (EEZ)': ['Kiribati'],
  'Navassa Island (EEZ)': ['United States'],
  'Cape Verde (EEZ)': ['Cabo Verde'],
  'Ivory Coast (EEZ)': ["Côte d'Ivoire"],
  'Russia (EEZ)': ['Russian Federation'],
  'Federal Republic of Somalia (EEZ)': ['Somalia'],
  'Comores (EEZ)': ['Comoros'],
  'Republic of the Congo (EEZ)': ['Congo'],
  'Timor Leste (EEZ)': ['Timor-Leste'],
  'Vietnam (EEZ)': ['Viet Nam'],
  'Ile Tromelin (EEZ)': ['France'],
  'La Reunion (EEZ)': ['Réunion'],
  'Matthew and Hunter Islands (EEZ)': ['France', 'Vanuatu'],
  'Clipperton Island (EEZ)': ['France'],
  'Guadeloupe (EEZ)': ['France'],
  'Saint Barthelemy (EEZ)': ['Saint Barthélemy'],
  'Collectivity of Saint Martin (EEZ)': ['Saint Martin (French part)'],
  'Saint-Pierre and Miquelon (EEZ)': ['Saint Pierre and Miquelon'],
  'Amsterdam and Saint Paul Islands (EEZ)': ['French Southern Territories'],
  'Falkland / Malvinas Islands (EEZ)': ['Falkland Islands (Malvinas)'],
  'St Helene, Ascension and Tristan da Cunha (EEZ)': ['Saint Helena'],
  'Guam (EEZ)': ['United States'],
  'Hawaii (EEZ)': ['United States'],
  'Alaska (EEZ)': ['United States'],
  'Palmyra Atoll (EEZ)': ['United States'],
  'Netherland (EEZ)': ['Netherlands'],
  'Caribbean Netherlands (EEZ)': ['Netherlands'],
  'Easter Islands (EEZ)': ['Chile'],
  'San Felix and San Ambrosia islands (EEZ)': ['Chile'],
  'Macquire Island (EEZ)': ['Australia'],
  'Heard and McDonald Islands (EEZ)': ['Heard Island and McDonald Islands'],
  'Cocos Islands (EEZ)': ['Cocos (Keeling) Islands'],
  'Christmas Islands (EEZ)': ['Christmas Island'],
  'Greenland (EEZ)': ['Denmark'],
};

// Every river basin -> the countries it spans (many-to-many). Country names
// match the YAML; any missing country (e.g. Germany on the Rhine/Danube) is
// skipped at build time.
export const riverBasinCountries: Record<string, string[]> = {
  'Indigirka (RB)': ['Russian Federation'],
  'Ob (RB)': ['Russian Federation', 'Kazakhstan', 'China', 'Mongolia'],
  'Brahmaputra (RB)': ['China', 'India', 'Bangladesh', 'Bhutan'],
  'Ganges (RB)': ['India', 'Bangladesh', 'Nepal', 'China'],
  'Indus (RB)': ['Pakistan', 'India', 'China', 'Afghanistan'],
  'Irrawaddy (RB)': ['Myanmar', 'China', 'India'],
  'Salween (RB)': ['China', 'Myanmar', 'Thailand'],
  'Kamchatka (RB)': ['Russian Federation'],
  'Mekong (RB)': ['China', 'Myanmar', 'Laos', 'Thailand', 'Cambodia', 'Viet Nam'],
  'Yangtze (RB)': ['China'],
  'Yellow River (RB)': ['China'],
  'Aral Sea (RB)': ['Kazakhstan', 'Uzbekistan', 'Tajikistan', 'Kyrgyzstan', 'Turkmenistan', 'Afghanistan'],
  'Chuy (RB)': ['Kyrgyzstan', 'Kazakhstan'],
  'Har Us Nuur (RB)': ['Mongolia'],
  'Lake Balkhash (RB)': ['Kazakhstan', 'China'],
  'Talas (RB)': ['Kyrgyzstan', 'Kazakhstan'],
  'Tarim He (RB)': ['China', 'Kyrgyzstan'],
  'Uvs Nuur (RB)': ['Mongolia', 'Russian Federation'],
  'Ysyk Kol (RB)': ['Kyrgyzstan'],
  'Amazon (RB)': ['Brazil', 'Peru', 'Colombia', 'Bolivia', 'Ecuador', 'Venezuela'],
  'Chico (RB)': ['Argentina'],
  'Colorado (RB)': ['Argentina'],
  'Magdalena (RB)': ['Colombia'],
  'Negro (RB)': ['Argentina', 'Uruguay'],
  'Santa Cruz (RB)': ['Argentina'],
  'Aisen (RB)': ['Chile'],
  'Azopardo (RB)': ['Chile', 'Argentina'],
  'Baker (RB)': ['Chile'],
  'Biobio (RB)': ['Chile'],
  'Cisnes (RB)': ['Chile'],
  'Copiapo (RB)': ['Chile'],
  'Huasco (RB)': ['Chile'],
  'Majes (RB)': ['Peru'],
  'Ocona (RB)': ['Peru'],
  'Palena (RB)': ['Chile', 'Argentina'],
  'Pascua (RB)': ['Chile'],
  'Puelo (RB)': ['Chile', 'Argentina'],
  'Rapel (RB)': ['Chile'],
  'Santa (RB)': ['Peru'],
  'Serrano (RB)': ['Chile'],
  'Valdivia (RB)': ['Chile'],
  'Yelcho (RB)': ['Chile', 'Argentina'],
  'Titicaca (RB)': ['Peru', 'Bolivia'],
  'Colville (RB)': ['United States'],
  'Mackenzie (RB)': ['Canada'],
  'Nelson (RB)': ['Canada', 'United States'],
  'Alsek (RB)': ['Canada', 'United States'],
  'Columbia (RB)': ['United States', 'Canada'],
  'Copper (RB)': ['United States'],
  'Fraser (RB)': ['Canada'],
  'Kuskokwim (RB)': ['United States'],
  'Nass (RB)': ['Canada'],
  'Nushagak (RB)': ['United States'],
  'Skagit (RB)': ['United States', 'Canada'],
  'Skeena (RB)': ['Canada'],
  'Stikine (RB)': ['Canada', 'United States'],
  'Susitna (RB)': ['United States'],
  'Taku (RB)': ['Canada', 'United States'],
  'Yukon (RB)': ['United States', 'Canada'],
  'Clutha (RB)': ['New Zealand'],
  'Jokulsa a Fjollum (RB)': ['Iceland'],
  'Lagarfljot (RB)': ['Iceland'],
  'Svarta (RB)': ['Iceland'],
  'Danube (RB)': ['Germany', 'Austria', 'Slovakia', 'Hungary', 'Croatia', 'Serbia', 'Romania', 'Bulgaria', 'Ukraine', 'Moldova', 'Bosnia and Herzegovina', 'Slovenia'],
  'Dramselva (RB)': ['Norway'],
  'Glomaa (RB)': ['Norway'],
  'Kalixalven (RB)': ['Sweden'],
  'Kuban (RB)': ['Russian Federation'],
  'Lulealven (RB)': ['Sweden'],
  'Olfusa (RB)': ['Iceland'],
  'Po (RB)': ['Italy', 'Switzerland', 'France'],
  'Rhine (RB)': ['Switzerland', 'Germany', 'France', 'Netherlands', 'Austria', 'Liechtenstein', 'Luxembourg', 'Belgium'],
  'Rhone (RB)': ['Switzerland', 'France'],
  'Thjorsa (RB)': ['Iceland'],
  'Tornealven (RB)': ['Sweden', 'Finland', 'Norway'],
};
