UPDATE indicators AS indicator
SET id = names.id
FROM (VALUES
  ('urbclim-T2M-dayoverX', 'Days a Year with Maximum Temperatures Above X°C'),
  ('urbclim-T2M-nightoverX', 'Nights a Year with Minimum Temperatures Above X°C'),
  ('urbclim-WBGT-dayover31', 'Days a Year with Extreme Heat Stress'),
  ('urbclim-WBGT-dayover295', 'Days a Year with Very High Heat Stress'),
  ('urbclim-WBGT-dayover25', 'Days a Year with Moderate Heat Stress'),
  ('urbclim-WBGT-dayover28', 'Days a Year with High Heat Stress'),
  ('urbclim-cooling-degree-hours', 'Cooling Degree Hours'),
  ('urbclim-WBGT-hourover31', 'Hours a Year with Extreme Heat Stress'),
  ('urbclim-T2M-daily-mean-max', 'Mean Daily Maximum Temperature'),
  ('urbclim-WBGT-nightover28', 'Nights a Year with High Heat Stress'),
  ('urbclim-LWH-mod', 'Lost Working Hours per Year for Moderate Activities'),
  ('urbclim-HWMI', 'Heat-Wave Magnitude Index Daily (HWMId)'),
  ('urbclim-T2M-daily-mean-min', 'Mean Daily Minimum Temperature'),
  ('urbclim-WBGT-hourover25', 'Hours a Year with Moderate Heat Stress'),
  ('urbclim-WBGT-daily-mean-max', 'Mean Daily Maximum Wet Bulb Globe Temperature'),
  ('urbclim-LWH-light', 'Lost Working Hours per Year for Light Activities'),
  ('urbclim-T2M-mean', 'Mean Daily Temperature'),
  ('urbclim-LWH-int', 'Lost Working Hours per Year for Intense Activities'),
  ('urbclim-WBGT-hourover28', 'Hours a Year with High Heat Stress'),
  ('urbclim-WBGT-hourover295', 'Hours a Year with Very High Heat Stress'),
  ('urbclim-heatwave-days', 'Heatwave Days per Year'),
  ('urbclim-heatwaves-population-exposed', 'Population Exposed to Heatwaves'),
  ('urbclim-heatstressimpact-wbgt-dayover25', 'Population Exposed to Moderate Heatstress'),
  ('urbclim-heatstressimpact-wbgt-dayover28', 'Population Exposed to High Heat Stress'),
  ('urbclim-heatstressimpact-wbgt-dayover295', 'Population Exposed to Very High Heat Stress'),
  ('urbclim-heatstressimpact-wbgt-dayover31', 'Population Exposed to Extreme Heatstress'),
  ('terclim-mean-temperature', 'Mean Temperature'),
  ('terclim-hot-extreme', 'Extremely Hot Year'),
  ('terclim-cold-extreme', 'Extremely Cold Year'),
  ('terclim-txx', 'Annual Maximum Temperature'),
  ('terclim-mrso-minmon', 'Annual Minimum of Monthly Mean Soil Moisture Content'),
  ('terclim-fwisa', 'Fire Weather Index During the Fire Season'),
  ('terclim-fwils', 'Length of the Fire Season'),
  ('terclim-mrso', 'Soil Moisture Content'),
  ('terclim-fwixx', 'Annual Maximum of the Fire Weather Index'),
  ('terclim-fwixd', 'Number of Days with Extreme Fire Weather'),
  ('biodiversity-srr', 'Species at Risk from Local Extinction'),
  ('biodiversity-timber-srr', 'Timber Species at Risk from Local Extinction'),
  ('biodiversity-pollinators-srr', 'Pollinator Species at Risk from Local Extinction'),
  ('biodiversity-plantae-srr', 'Plant Species at Risk from Local Extinction'),
  ('glacier-area', 'Glacier Area'),
  ('glacier-volume', 'Glacier Volume'),
  ('glacier-thinning_rate', 'Glacier Thinning Rate'),
  ('urbclim-WBGT-nightover25', 'Nights a Year with Moderate Heat Stress'),
  ('marclim-sst', 'Sea Surface Temperature'),
  ('marclim-ph', 'Sea Surface pH'),
  ('marclim-oxygen', 'Ocean Oxygen Content'),
  ('marclim-sst_ext', 'Marine Heatwave Days per Year'),
  ('carboncycle-d-ch4', 'Global Atmospheric CH4 Concentration from Peatland Emissions'),
  ('carboncycle-d-co2', 'Global Atmospheric CO2 Concentration from Peatland Emissions'),
  ('carboncycle-d-ept-ch4', 'Peatland CH4 Emission'),
  ('carboncycle-d-ept-co2', 'Peatland CO2 Flux'),
  ('carboncycle-d-tg', 'Global Annual Mean Temperature Rise from Peatland Emissions'),
  ('macroeconomy-bhm', 'Climate Change Impact on GDP'),
  ('macroeconomy-export-supply-food', 'Export Supply (Food Sector)'),
  ('macroeconomy-export-supply-livestock', 'Export Supply (Livestock Sector)'),
  ('macroeconomy-export-supply-manufacturing', 'Export Supply (Manufacturing Sector)'),
  ('macroeconomy-export-supply-services', 'Export Supply (Services Sector)'),
  ('macroeconomy-private-consumption-food', 'Private Consumption (Food Sector)'),
  ('macroeconomy-private-consumption-livestock', 'Private Consumption (Livestock Sector)'),
  ('macroeconomy-private-consumption-manufacturing', 'Private Consumption (Manufacturing Sector)'),
  ('macroeconomy-private-consumption-services', 'Private Consumption (Services Sector)'),
  ('macroeconomy-gdp-macro', 'GDP (All Sectors)'),
  ('macroeconomy-import-demand-food', 'Import Demand (Food Sector)'),
  ('macroeconomy-import-demand-livestock', 'Import Demand (Livestock Sector)'),
  ('macroeconomy-import-demand-manufacturing', 'Import Demand (Manufacturing Sector)'),
  ('macroeconomy-import-demand-services', 'Import Demand (Services Sector)'),
  ('macroeconomy-producer-price-food', 'Producer Price (Food Sector)'),
  ('macroeconomy-producer-price-livestock', 'Producer Price (Livestock Sector)'),
  ('macroeconomy-producer-price-manufacturing', 'Producer Price (Manufacturing Sector)'),
  ('macroeconomy-producer-price-services', 'Producer Price (Services Sector)'),
  ('macroeconomy-wages-food', 'Wages (Food Sector)'),
  ('macroeconomy-wages-livestock', 'Wages (Livestock Sector)'),
  ('macroeconomy-wages-manufacturing', 'Wages (Manufacturing Sector)'),
  ('macroeconomy-wages-services', 'Wages (Services Sector)'),
  ('macroeconomy-consumer-price-index-macro', 'Consumer Price Index (All Sectors)'),
  ('macroeconomy-production-food', 'Production (Food Sector)'),
  ('macroeconomy-production-livestock', 'Production (Livestock Sector)'),
  ('macroeconomy-production-manufacturing', 'Production (Manufacturing Sector)'),
  ('macroeconomy-production-services', 'Production (Services Sector)'),
  ('macroeconomy-labour-productivity', 'Labour Productivity'),
  ('urbclim-WBGT-nightoverX', 'Nights a Year Where Minimum Wet-Bulb Globe Temperatures Stay Above X°C'),
  ('urbclim-WBGT-houroverX', 'Hours a Year with Maximum Wet-Bulb Globe Temperature Above X°C'),
  ('urbclim-T2M-daily-mean-max-topography', 'Daytime Urban Heat Island Corrected for Topography'),
  ('urbclim-T2M-daily-mean-min-topography', 'Nighttime Urban Heat Island Corrected for Topography')
) AS names(legacy_uid, id)
WHERE indicator.legacy_uid = names.legacy_uid
  AND indicator.id IS DISTINCT FROM names.id;
